/**
 * The ladder the card tiles are sized on, and the three sums every surface that draws them
 * needs.
 *
 * ## Why a ladder and not a multiplier
 *
 * The gesture behind this is ctrl+wheel, and **a wheel delta is not a magnitude anything may
 * trust**. A mouse notch arrives as a `deltaY` of 100 through Chromium's line mode and as 120
 * from a driver reporting raw ticks; a precision trackpad's pinch — which reaches the page as
 * a *stream* of ctrl-flagged wheel events, not as a gesture of its own — arrives in the single
 * digits, dozens of times a second. Scaling by the delta would make one flick of the wrist mean
 * four different things across the hardware a single reader owns, and would take the pinch from
 * one end of the range to the other before they let go. A ladder makes the unit the **gesture**:
 * one wheel event is one stop, whatever the hardware called it.
 *
 * It also keeps the number exact, which a multiplier cannot. `zoom * 1.1` applied eight times
 * and undone eight times is not 1 — it is 0.9999999999999998, which formats as "100%" while
 * sizing every tile a hair off and never lands back on a value the ladder could leave.
 * {@link stepZoom} returns an element of {@link ZOOM_STEPS} *by identity*, so the state can only
 * ever hold one of sixteen exact numbers and `zoom === 1` is a question worth asking. The same
 * argument is why the stops are written out as literals rather than generated by adding 0.1
 * sixteen times, which drifts in exactly the way it warns about.
 *
 * ## Where the state lives
 *
 * Not here. This module is arithmetic — the values are `useAppStore`'s `cardZoom`, which holds
 * **one number per card section** ({@link ZOOM_SECTIONS}) rather than one for the app. A reader
 * zooming the deck editor's docked search column was resizing the deck laid out beside it, and
 * those are two different questions asked in the same second; the ladder below is the same ladder
 * either way, it is just walked once per section.
 *
 * ## They outlive the process, which reverses what this file used to say
 *
 * The old rule was that every section was session-only — "zoom is a posture a reader takes for a
 * minute of comparing art, not a preference they set once; restoring it on launch would mean a
 * reader who peered at one card in the last session is greeted by 200% tiles in the next one,
 * with nothing on screen explaining why." Readers asked for the opposite (issue #175), and the
 * argument had a hole in it: it was written when there was **one** number for the whole app, so
 * "the zoom" really was a momentary posture that a single card could set for every wall at once.
 * Split per section it is not that any more. A reader who sizes the deck editor so a 100-card pile
 * fits the desk, or the Tags wall up so an illustration is legible, has configured *that wall* —
 * and the app forgetting it on every launch was the complaint.
 *
 * What is left of the old worry is the 200% surprise, and the split answers that too: a size
 * chosen on one wall is restored to that wall and nowhere else, so nothing a reader did in the
 * printings modal is waiting for them on the search page. `src/lib/useCardZoomPersistence.ts` is
 * the whole of the mechanism — one `app_meta` row, read once at launch, written on a trailing
 * timer after a gesture stops.
 */

/**
 * Sixteen stops from half size to double, **evenly spaced ten points apart**.
 *
 * ## Why even, when a browser's zoom menu is not
 *
 * This replaced a ten-stop ladder shaped like a browser's own menu — `0.5, 0.67, 0.75, 0.9, 1,
 * 1.1, 1.25, 1.5, 1.75, 2` — coarse at the ends and fine either side of 100%. The argument for
 * that shape was that the stops near 1 are where a reader is actually steering, and it is still
 * true; what it got wrong is that a browser's ladder is walked by *pressing a key*, where each
 * press is a deliberate act and the menu shows you the list. This one is walked by **rolling a
 * wheel**, where the stops go past in a continuous run — and an uneven ladder rolled quickly is a
 * gesture whose speed changes under the reader's hand for no reason they can see. Above 1 the old
 * ladder went 10, 15, 25, 25, 25 points a notch: the same wrist movement moved the cards two and
 * a half times as far at the top as at the bottom.
 *
 * Even spacing costs the top of the range some reach — 200% is now ten notches up from life size
 * rather than five — and buys the thing a wheel gesture needs, which is that one notch always
 * means the same amount. It also makes every stop a round number a reader can name: the badge
 * reads 50%, 60%, 70% … 200% and nothing else.
 *
 * ## The numbers are spelled out, not generated
 *
 * A loop adding 0.1 sixteen times is exactly the drift {@link stepZoom} exists to avoid — 0.1
 * added seven times is 0.7999999999999999, which formats as "80%" while sizing every tile a hair
 * off and never landing on a value the ladder could leave. Written as literals each stop is the
 * nearest double to the decimal a reader reads, and {@link stepZoom} returns them **by identity**,
 * so the state can only ever hold one of sixteen exact numbers.
 */
export const ZOOM_STEPS = [
  0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2,
] as const;

/**
 * Tiles at the size every surface drew them before this existed. Also where a section starts when
 * the database has never been told otherwise — which is every section of a fresh install, and any
 * one whose stored entry could not be read.
 */
export const DEFAULT_ZOOM = 1;

/** The bottom of {@link ZOOM_STEPS} — read from the ladder so the two cannot drift. */
export const MIN_ZOOM: number = ZOOM_STEPS[0];

/** The top of {@link ZOOM_STEPS}. */
export const MAX_ZOOM: number = ZOOM_STEPS[ZOOM_STEPS.length - 1];

/**
 * The card sections that zoom independently of one another.
 *
 * Five surfaces draw walls of cards, and they share the screen rather than taking turns on it:
 * the deck editor puts its docked card search column beside the deck itself, and the printings
 * modal opens over whichever wall is already up. One shared number made a gesture over the
 * search column resize the deck too — "how big are the cards I am browsing" and "how big is my
 * deck laid out" answered together, when the reader only asked one of them.
 *
 * `deck` is one key for **both** deck views. Stacks and Grid are two drawings of the same pile,
 * so switching between them must not resize the cards the reader just settled on.
 *
 * `printings` is the all-printings modal's wall, and it is the strongest case on the list rather
 * than the weakest: the modal opens **over** a wall the reader has already sized, so a shared
 * number would have a ctrl+wheel inside it resize the page underneath — a change made to
 * something they cannot see, waiting for them when the modal closes. It is the one section that
 * is not a place a reader navigates to, and it is still a section for that reason: the modal
 * throws away its filter and its scroll on every close, and the size the cards are drawn at is
 * the one thing about it a reader would resent re-setting.
 *
 * `deckGallery` is the decks page — the wall of deck tiles and folder cards, which is the one
 * surface on this list whose tiles are not cards. It is a wall of **art** all the same, and the
 * reader's question there is the one every other section answers: how many of these do I want on
 * screen at once, against how well I want to see each one. **Named `deckGallery` rather than
 * `decks`, and the name is doing work**: `deck` is already the section the editor's cards are
 * drawn at, both keys are read inside `features/decks/`, and two keys one character apart are a
 * typo that steps a wall the reader is not looking at — which reads as a gesture that does
 * nothing rather than as a mistake.
 */
export const ZOOM_SECTIONS = [
  "search",
  "tags",
  "collection",
  "wishlist",
  "deckSearch",
  "deck",
  "deckGallery",
  "printings",
] as const;

export type ZoomSection = (typeof ZOOM_SECTIONS)[number];

/**
 * Every section at {@link DEFAULT_ZOOM} — the shape `cardZoom` is **built** as, before anything
 * stored has been read.
 *
 * Still the literal starting point even though the sections persist, and deliberately: the read
 * is a round trip and the store has to hold a complete, drawable `Record<ZoomSection, number>` from
 * its first frame. A section the database has nothing to say about keeps the value it was built
 * with, which is what makes a fresh install, a failed read and a hand-emptied row all land in the
 * same place without a branch anywhere.
 *
 * Spelled out as a literal rather than reduced over {@link ZOOM_SECTIONS}, because
 * `Record<ZoomSection, number>` then makes a new section a **compile error** until somebody has
 * said what it starts at. A `reduce` would quietly hand it whatever the reduce's default was, and
 * a section nobody chose a starting size for is exactly the thing worth stopping a build over.
 */
export const DEFAULT_SECTION_ZOOMS: Readonly<Record<ZoomSection, number>> = {
  search: DEFAULT_ZOOM,
  // The Tags page's wall. Its own key rather than the search's for the reason every split on
  // this list has: the two walls are never on screen together, but they are read for different
  // reasons — one to find a card by name, one to look at what a motif's illustrations *are* —
  // and a reader who sized the art up to read a picture was not resizing a search by name.
  tags: DEFAULT_ZOOM,
  collection: DEFAULT_ZOOM,
  // The shopping list's wall. Its own key rather than the collection's for the reason every
  // split on this list has: the two are read one after the other — what is wanted, then what
  // is owned — and a size settled on one is not an answer about the other.
  wishlist: DEFAULT_ZOOM,
  deckSearch: DEFAULT_ZOOM,
  deck: DEFAULT_ZOOM,
  // The decks page's wall of tiles and folder cards. A whole deck rather than a card, so it is
  // the one section here whose default is a statement about a 626px art crop and a name under
  // it rather than about a 5:7 face.
  deckGallery: DEFAULT_ZOOM,
  // The modal's wall. Its own key rather than the search's, for {@link ZOOM_SECTIONS}' own
  // reason: the modal opens *over* a wall the reader has already sized, and a ctrl+wheel inside
  // it must not resize the page underneath.
  printings: DEFAULT_ZOOM,
};

/**
 * The stop nearest `zoom`, so an off-ladder value has somewhere to step *from*.
 *
 * Nothing writes an off-ladder value today, and the snap is still the honest reading of the
 * question: a caller asking for the next stop up from 1.05 means 1.1, not "1.05 is not on the
 * ladder". A tie goes to the lower stop (`<`, not `<=`), which makes a value exactly between two
 * stops step *up* to the higher and *down* to the lower — the direction the reader asked for
 * either way.
 */
function nearestIndex(zoom: number): number {
  let best = 0;
  for (let i = 1; i < ZOOM_STEPS.length; i++) {
    if (Math.abs(ZOOM_STEPS[i] - zoom) < Math.abs(ZOOM_STEPS[best] - zoom)) best = i;
  }
  return best;
}

/**
 * The stop nearest `zoom` — the ladder's answer to a number that came from outside it.
 *
 * Exists because the zoom is stored now, and a stored number is not one of the ten by
 * construction the way a stepped one is. Three things can put an off-ladder value in the row: a
 * build whose ladder was spaced differently, a hand-edited `mtg.db`, and Rust's own bound, which
 * checks that a value is between 0.5 and 2 and deliberately does not know where the stops are.
 * Snapping on the way in is what keeps the invariant `stepZoom` was written for — `cardZoom` holds
 * one of sixteen exact numbers, so `zoom === 1` is a question worth asking — true of a *restored*
 * session as well as a fresh one.
 *
 * A value that is not a finite number has no nearest stop and is not a zoom, so it comes back as
 * {@link DEFAULT_ZOOM}: `NaN` compares false against everything, which would otherwise walk
 * {@link nearestIndex} straight to index 0 and hand a reader 50% tiles for a corrupt row.
 */
export function snapZoom(zoom: number): number {
  if (!Number.isFinite(zoom)) return DEFAULT_ZOOM;
  return ZOOM_STEPS[nearestIndex(zoom)];
}

/**
 * Is this string one of the walls that zoom?
 *
 * The gate on anything read back out of storage. The row is a JSON object whose keys are whatever
 * some build of this app wrote, so a section that has since been renamed or removed arrives here
 * as an ordinary string — and quietly writing it into `cardZoom` would put a key in a
 * `Record<ZoomSection, number>` that the type says cannot be there.
 */
export function isZoomSection(value: string): value is ZoomSection {
  return (ZOOM_SECTIONS as readonly string[]).includes(value);
}

/**
 * One stop in `direction` — `1` bigger, `-1` smaller — clamped at both ends of the ladder.
 *
 * **At a limit it returns the value it was given**, rather than refusing or wrapping. That is the
 * whole of the clamp, and it is why the store increments its pulse separately: a reader holding
 * the wheel at 200% goes on producing gestures that this function answers with 200% forever, and
 * the badge that tells them so must not read "no change" as "no gesture".
 */
export function stepZoom(current: number, direction: 1 | -1): number {
  const from = nearestIndex(current);
  const next = from + direction;
  if (next < 0 || next >= ZOOM_STEPS.length) return ZOOM_STEPS[from];
  return ZOOM_STEPS[next];
}

/**
 * The zoom as a reader reads it: `"120%"`.
 *
 * Rounded to a whole percent because a decimal that is round on paper need not be round in
 * binary: 1.1 times 100 is 110.00000000000001, and printed raw that stop would show a badge
 * fourteen digits wide. Exactly one of the sixteen misbehaves today, and the rounding stays
 * anyway — **which** stop drifts is an accident of where the literals land against a double, not
 * something a ladder can be designed out of, so a rule that held only while the arithmetic
 * happened to agree would be no rule at all. There is no locale in this: a percentage on a HUD is
 * a magnitude, and `formatPrice`'s argument about currency does not reach it.
 */
export function formatZoom(zoom: number): string {
  return `${Math.round(zoom * 100)}%`;
}

/**
 * A base pixel measurement at this zoom, as a whole number of pixels.
 *
 * Rounded rather than left fractional because these numbers become grid track widths and image
 * box heights, and a fractional one is a seam: the browser snaps each tile's *painted* edge on
 * its own, so a column of 212.5px tiles alternates 212 and 213 down the page and the 5:7 art
 * boxes stop lining up across a row. One rounding here, at the one place the multiplication
 * happens, keeps every consumer of the same `base` in agreement.
 *
 * Half rounds up, which is JavaScript's rule and not a choice made here — `scaled(170, 1.25)`
 * is 213.
 */
export function scaled(base: number, zoom: number): number {
  return Math.round(base * zoom);
}

/**
 * A base that **grows with the zoom and never shrinks below itself** — the rule for exactly one
 * kind of measurement on a wall of cards: the gutter between them.
 *
 * It used to govern a tile's foot and the type in it as well, on the argument that the card is a
 * picture and scales in both directions honestly while the things around it do not. That was true
 * while they did not: a 9px caption under a halved card would have become 4px, which is not type.
 * It is false now — the caption, the gem, the copy count and the stepper all follow
 * {@link MARK_SCALE_VAR} — so a floored budget is a 20px strip around 5px of type, which is the
 * same fault the other way up.
 *
 * The gutter keeps the floor because it is the one measurement **between** cards rather than **on**
 * one: it is what stops a wall reading as one sheet, and halving it at 0.5× is precisely the zoom a
 * reader chose in order to see more cards at once. Nothing is being contained, so there is nothing
 * for it to stay in step with.
 *
 * Lifted out of `features/decks/views/GridView.tsx` on 2026-08-26, when the decks gallery became
 * the second wall to need it. It is one rule about how gutters behave under a zoom, and two
 * copies of it would be two walls that agree today.
 */
export function atLeast(base: number, zoom: number): number {
  return Math.max(base, scaled(base, zoom));
}

/**
 * The custom property every mark laid on a card reads to size itself: the reader's zoom, as a
 * bare number, inherited down from the card's own root element.
 *
 * ## Why a CSS variable and not a prop
 *
 * The marks are shared components and **most of their call sites must not scale**. `RarityGem` is
 * drawn on a wall tile, in a deck tile's foot, in the stack's data line — and in the search table,
 * the collection table, the wishlist table and the card pane twice. `OwnedBadge`, `FinishMark`,
 * `TagDot` and `QuantityStepper` are each split the same way. A prop would have to be threaded to
 * every one of them and *defaulted* at the ones that stay still, which makes "does this scale?" a
 * question answered fifteen times, silently, by whoever added the newest call site.
 *
 * An inherited custom property answers it once, in the other direction: a mark reads
 * `var(--mark-scale, 1)`, and the fallback is what every surface that is not a card gets **without
 * knowing this variable exists**. Three elements set it — `CardGrid`'s tile, `GridView`'s tile and
 * `CardStack`'s card — and nothing else in the app has to be touched for a table to keep drawing
 * a 12px gem.
 *
 * It is also the reason this is not a `transform: scale()` on the overlay layer, which would have
 * been one line per corner: the caption strip under a wall tile is **in flow**, and a transform
 * changes no layout at all — the text would grow straight out of the strip the virtualiser sized
 * its rows from. Real geometry is the standing rule here (`src/CLAUDE.md`) and it is the only one
 * that works for both halves of a tile.
 *
 * ## It scales in both directions, unlike the budgets that hold it
 *
 * There is no floor. That is a deliberate reversal of `atLeast` — the `max(base, scaled(base))`
 * rule that governed `CardGrid`'s caption, `GridView`'s foot, `stackAdvance` and
 * `stackDataHeight` — and the reversal is what those floors were *for*: each one existed because
 * the chrome inside it could not shrink, so the budget had to refuse to. Now that the chrome
 * shrinks with the card, a floored budget is a 28px strip around 6px of type. The floors that
 * remain are the ones measuring space **between** cards rather than chrome **on** them — the two
 * walls' gutters — where nothing is being contained and the old argument still holds.
 */
export const MARK_SCALE_VAR = "--mark-scale";

/**
 * The same idea for the controls drawn on a card — the wall tile's quick-add, the deck tile's
 * stepper, the stack card's stepper column — kept a **separate** number because they are drawn a
 * little smaller than their panel-sized twins.
 *
 * One variable could not say this. The stepper's `xs` size is drawn in a deck tile's foot *and* in
 * the table and text views' rows, and the quick-add trigger is drawn in a wall tile's caption *and*
 * in the search table *and* in the card pane's printings rows — so baking {@link CONTROL_SHRINK}
 * into the control's own base would shrink four surfaces nobody asked about. Carried as a second
 * variable it reaches exactly the three roots that set it, and everywhere else the `, 1` fallback
 * leaves the control the size it has always been.
 */
export const CONTROL_SCALE_VAR = "--control-scale";

/**
 * How much smaller a control is when it is drawn **on a card** rather than in a panel or a row.
 *
 * A control on a card is competing with somebody's artwork for the same two square centimetres,
 * and it is revealed on hover rather than resident — so it does not have to hold the presence a
 * table's stepper does. 85% is the largest reduction that leaves the wall tile's quick-add above
 * 20px at 1×, which is the smallest square this app asks anyone to hit.
 */
export const CONTROL_SHRINK = 0.85;

/**
 * The two variables above, as the `style` object a card's root element carries.
 *
 * Written as one function rather than spelled at three call sites because the pair has to move
 * together: a mark and the control beside it in the same caption reading two different zooms is
 * the kind of drift that looks like a rendering fault. The cast is `CSSProperties`' doing — React
 * types custom properties as unknown keys, and there is no narrower way to say "these two".
 */
export function cardScaleVars(zoom: number): Record<string, string> {
  return {
    [MARK_SCALE_VAR]: String(zoom),
    [CONTROL_SCALE_VAR]: String(zoom * CONTROL_SHRINK),
  };
}
