/**
 * The fence between this writer and the one in `src-tauri/src/transfer/`.
 *
 * The files under `__golden__/` are generated by `npm run golden` and committed. This suite
 * asserts the TypeScript writer still reproduces them; `src-tauri/src/transfer/write.rs`'s own
 * suite asserts the Rust writer reproduces the same bytes. A change to either writer is a red
 * suite, which is the whole point — so a red case here is answered by arguing with the writer,
 * never by re-running the generator to bless whatever it now emits.
 *
 * **Read through Vite's `?raw` rather than through `node:fs`**, which is not a preference: this
 * project installs no `@types/node` on purpose (`tsconfig.json`'s `"types": []` and the note
 * above it), so `src/` cannot see `node:fs` at all and `tsc` would refuse the obvious spelling.
 * `lib/tokens.test.ts` reaches for the same two tools — a `?raw` import for one known file and
 * `import.meta.glob` for a directory of them — and the glob is what lets the first case below
 * notice a golden file that exists on disk and belongs to no case.
 */
import { describe, expect, it } from "vitest";
import { formatExport, omittedCount } from "./export/format";
import { availableFields, defaultFields, type TransferSurface } from "./fields";
import { EXPORT_FORMATS } from "./formats";
import { parseDecklist } from "./import/parse";
import type { TransferCard } from "./TransferCard";
import corpusText from "./__golden__/corpus.json?raw";

/** Where the glob's keys start. They are project-absolute, so the file name is the tail. */
const DIR = "/src/features/transfer/__golden__";

/**
 * Every golden file, as text.
 *
 * Eager and absolute for `tokens.test.ts`' reason — a lazy glob would hand back promises no
 * `it.each` case can await synchronously, and a relative pattern's keys drift with this file.
 */
const GOLDEN = import.meta.glob<string>("/src/features/transfer/__golden__/*.txt", {
  query: "?raw",
  import: "default",
  eager: true,
});

const corpus = JSON.parse(corpusText) as {
  scenarios: Record<string, { surface: TransferSurface; cards: TransferCard[] }>;
};

const CASES = Object.entries(corpus.scenarios).flatMap(([scenario, { surface, cards }]) =>
  EXPORT_FORMATS.flatMap((format) =>
    (["all", "default"] as const).map((setName) => ({
      file: `${scenario}.${format}.${setName}.txt`,
      cards,
      format,
      fields: setName === "all" ? availableFields(format, surface) : defaultFields(format, surface),
    })),
  ),
);

describe("the golden corpus", () => {
  it("has a file for every scenario, format and field set, and no others", () => {
    const onDisk = Object.keys(GOLDEN)
      .map((path) => path.slice(DIR.length + 1))
      .sort();
    expect(onDisk).toEqual(CASES.map((c) => c.file).sort());
  });

  it.each(CASES)("reproduces $file", ({ file, cards, format, fields }) => {
    expect(formatExport(cards, format, fields)).toBe(GOLDEN[`${DIR}/${file}`]);
  });

  /**
   * An empty list is an empty string in every format, CSV's header included — and a deck that
   * is entirely maybeboard is the same answer in the two formats that write only switched-on
   * piles. Asserted by *size* rather than by content because that is the claim: a lone newline
   * would satisfy `toBe("")` after a trim and would not be an empty file.
   */
  it("writes nothing at all for a list that has nothing to say", () => {
    const empty = Object.entries(GOLDEN)
      .filter(([, text]) => text === "")
      .map(([path]) => path.slice(DIR.length + 1))
      .sort();
    expect(empty).toEqual(
      [
        ...EXPORT_FORMATS.flatMap((f) => [`empty.${f}.all.txt`, `empty.${f}.default.txt`]),
        ...(["arena", "mtgo"] as const).flatMap((f) => [
          `allMaybeboard.${f}.all.txt`,
          `allMaybeboard.${f}.default.txt`,
        ]),
      ].sort(),
    );
  });
});

/**
 * TCGplayer is the one write-only format — `parse.ts`' printing hint is `(SET) 123` and Mass
 * Entry's is `[SET] 123`, so `1 Bolt [LEA] 161` reads back as one long card name. CSV is left
 * out for the opposite reason: it is read by `parseCsvGrid`, which is a different code path
 * with its own tests in `parse.test.ts`, and asserting it here would say nothing about what
 * the decklist grammar can take.
 */
const READABLE = EXPORT_FORMATS.filter((f) => f !== "tcgplayer" && f !== "csv");

describe("what the mirror writes, the app can read", () => {
  const cards = corpus.scenarios.deck.cards;
  const copies = cards.reduce((n, c) => n + c.quantity, 0);

  it.each(READABLE)("parses the deck scenario back out of %s", (format) => {
    const parsed = parseDecklist(GOLDEN[`${DIR}/deck.${format}.all.txt`]);
    expect(parsed.issues).toEqual([]);
    expect(parsed.lines.length).toBeGreaterThan(0);
    for (const line of parsed.lines) expect(line.name).not.toBe("");
    // Every copy written comes back, and the only copies not written are the ones the format
    // itself leaves out — which is the number the dialog prints beside it.
    expect(parsed.totalCards).toBe(copies - omittedCount(cards, format));
  });
});
