/**
 * The fence between this writer and the one in `src-tauri/src/transfer/`.
 *
 * The files under `__golden__/` are generated by `npm run golden` and committed. This suite
 * asserts the TypeScript writer still reproduces them; `src-tauri/src/transfer/write.rs`'s own
 * suite asserts the Rust writer reproduces the same bytes. A change to either writer is a red
 * suite, which is the whole point — so a red case here is answered by arguing with the writer,
 * never by re-running the generator to bless whatever it now emits.
 *
 * **Read through Vite's `?raw` rather than through `node:fs`**, which is not a preference: this
 * project installs no `@types/node` on purpose (`tsconfig.json`'s `"types": []` and the note
 * above it), so `src/` cannot see `node:fs` at all and `tsc` would refuse the obvious spelling.
 * `lib/tokens.test.ts` reaches for the same two tools — a `?raw` import for one known file and
 * `import.meta.glob` for a directory of them — and the glob is what lets the first case below
 * notice a golden file that exists on disk and belongs to no case.
 */
import { describe, expect, it } from "vitest";
import { formatExport, omittedCount } from "./export/format";
import {
  availableFields,
  defaultFields,
  SURFACE_FIELDS,
  type TransferFieldId,
  type TransferSurface,
} from "./fields";
import { EXPORT_FORMATS } from "./formats";
import { transferCard } from "./fixtures";
import { parseDecklist } from "./import/parse";
import type { TransferCard } from "./TransferCard";
import corpusText from "./__golden__/corpus.json?raw";
import fieldsText from "./__golden__/fields.json?raw";

/** Where the glob's keys start. They are project-absolute, so the file name is the tail. */
const DIR = "/src/features/transfer/__golden__";

/**
 * Every golden file, as text.
 *
 * Eager and absolute for `tokens.test.ts`' reason — a lazy glob would hand back promises no
 * `it.each` case can await synchronously, and a relative pattern's keys drift with this file.
 */
const GOLDEN = import.meta.glob<string>("/src/features/transfer/__golden__/*.txt", {
  query: "?raw",
  import: "default",
  eager: true,
});

const corpus = JSON.parse(corpusText) as {
  scenarios: Record<string, { surface: TransferSurface; cards: TransferCard[] }>;
};

const CASES = Object.entries(corpus.scenarios).flatMap(([scenario, { surface, cards }]) =>
  EXPORT_FORMATS.flatMap((format) =>
    (["all", "default"] as const).map((setName) => ({
      file: `${scenario}.${format}.${setName}.txt`,
      cards,
      format,
      fields: setName === "all" ? availableFields(format, surface) : defaultFields(format, surface),
    })),
  ),
);

/**
 * Every field a `TransferCard` has, **read off a value rather than written out here.**
 *
 * `fixtures.ts`' `transferCard()` returns an object literal against an explicit `TransferCard`
 * return type, and the interface has no optional members — `null` is how it spells absence, as
 * its own header says. So the compiler moves that literal in both directions: a field added to
 * `TransferCard` makes the literal incomplete, and a field removed from it makes the literal
 * carry an excess property. Either way `fixtures.ts` stops compiling until somebody fixes it,
 * and the moment they do, `Object.keys` here changes and the case below goes red until
 * `corpus.json` is fixed too.
 *
 * That chain is the point. Task 2's Rust struct reads `corpus.json` with `deny_unknown_fields`,
 * which only fires on a key Rust has never heard of — it cannot see a field TypeScript grew and
 * the corpus never learned, because that field is simply absent from the JSON. This case is the
 * half of the fence that faces the other way.
 */
const FIELDS = Object.keys(transferCard()).sort();

describe("the corpus itself", () => {
  it("names every TransferCard field on every card, and no others", () => {
    const cards = Object.values(corpus.scenarios).flatMap((s) => s.cards);
    expect(cards.length).toBeGreaterThan(0);
    const odd = cards
      .map((card) => ({
        card: card.name,
        missing: FIELDS.filter((f) => !(f in card)),
        extra: Object.keys(card).filter((k) => !FIELDS.includes(k)),
      }))
      .filter((row) => row.missing.length > 0 || row.extra.length > 0);
    expect(odd).toEqual([]);
  });

  /**
   * A named category is one row of `deck_categories`, and `idx_deck_categories_grain` is
   * `UNIQUE (deck_id, name)` — so `kind` and `is_active` are facts about *the category*, not
   * about each card filed under it. Two cards naming one category and disagreeing about either
   * is a state the database cannot hold, and a golden file pinning what the writer does with
   * one would be a fence around a case that can never arrive.
   *
   * This exists because the corpus had exactly that: two `Sol Ring` rows both in `Artifacts`,
   * one active and one not, folding in twelve deck goldens. Caught in review rather than by a
   * test, which is what this case changes.
   */
  it("never lets one category name disagree with itself about kind or active", () => {
    const conflicts: string[] = [];
    for (const [scenario, { cards }] of Object.entries(corpus.scenarios)) {
      const grainOf = new Map<string, string>();
      for (const card of cards) {
        if (card.categoryName === null) continue;
        const grain = JSON.stringify([card.categoryKind, card.categoryActive]);
        const seen = grainOf.get(card.categoryName);
        if (seen === undefined) grainOf.set(card.categoryName, grain);
        else if (seen !== grain) {
          conflicts.push(`${scenario}/${card.categoryName}: ${seen} vs ${grain}`);
        }
      }
    }
    expect(conflicts).toEqual([]);
  });
});

const fieldsGolden = JSON.parse(fieldsText) as {
  surfaces: Record<TransferSurface, TransferFieldId[]>;
  available: Record<string, TransferFieldId[]>;
  default: Record<string, TransferFieldId[]>;
};

/**
 * **The registry fence, one level above the rendered bytes — and the hole it closes cannot be
 * closed by any `.txt` file.**
 *
 * `writeLine` renders exactly seven ids, so every other id is invisible in the six line
 * formats. Adding `lang` to `plain`'s `optional` on one side alone moves **zero golden bytes**
 * while changing the *fold key*, which would need two corpus rows differing solely in that
 * field to show up — and none exist. One printing held in two languages would then export as
 * two lines from the mirror and one line from this dialog, with all 70 files and both suites
 * green. Spec §6's "skipping the Rust half is a red `cargo test`" was true of CSV alone, whose
 * header row *is* `availableFields` spelled out.
 *
 * So `fields.json` commits the tables themselves in the shape that already works: written by
 * `npm run golden` from this side, asserted here and by `fields.rs`'s cargo suite. It is a
 * fence against *drift*, and only against drift — a table edited on both sides and regenerated
 * is a deliberate change, which is what regenerating a golden always means.
 */
describe("the registry golden", () => {
  it("is what this build's field tables answer", () => {
    expect(fieldsGolden.surfaces).toEqual(SURFACE_FIELDS);
    const available: Record<string, TransferFieldId[]> = {};
    const byDefault: Record<string, TransferFieldId[]> = {};
    for (const format of EXPORT_FORMATS) {
      for (const surface of Object.keys(SURFACE_FIELDS) as TransferSurface[]) {
        available[`${format}.${surface}`] = availableFields(format, surface);
        byDefault[`${format}.${surface}`] = defaultFields(format, surface);
      }
    }
    expect(fieldsGolden.available).toEqual(available);
    expect(fieldsGolden.default).toEqual(byDefault);
    expect(Object.keys(available)).toHaveLength(EXPORT_FORMATS.length * 3);
  });
});

describe("the golden corpus", () => {
  it("has a file for every scenario, format and field set, and no others", () => {
    const onDisk = Object.keys(GOLDEN)
      .map((path) => path.slice(DIR.length + 1))
      .sort();
    expect(onDisk).toEqual(CASES.map((c) => c.file).sort());
  });

  it.each(CASES)("reproduces $file", ({ file, cards, format, fields }) => {
    expect(formatExport(cards, format, fields)).toBe(GOLDEN[`${DIR}/${file}`]);
  });

  /**
   * An empty list is an empty string in every format, CSV's header included — and a deck that
   * is entirely maybeboard is the same answer in the two formats that write only switched-on
   * piles. Asserted by *size* rather than by content because that is the claim: a lone newline
   * would satisfy `toBe("")` after a trim and would not be an empty file.
   */
  it("writes nothing at all for a list that has nothing to say", () => {
    const empty = Object.entries(GOLDEN)
      .filter(([, text]) => text === "")
      .map(([path]) => path.slice(DIR.length + 1))
      .sort();
    expect(empty).toEqual(
      [
        ...EXPORT_FORMATS.flatMap((f) => [`empty.${f}.all.txt`, `empty.${f}.default.txt`]),
        ...(["arena", "mtgo"] as const).flatMap((f) => [
          `allMaybeboard.${f}.all.txt`,
          `allMaybeboard.${f}.default.txt`,
        ]),
      ].sort(),
    );
  });
});

/**
 * TCGplayer is the one write-only format — `parse.ts`' printing hint is `(SET) 123` and Mass
 * Entry's is `[SET] 123`, so `1 Bolt [LEA] 161` reads back as one long card name. CSV is left
 * out for the opposite reason: it is read by `parseCsvGrid`, which is a different code path
 * with its own tests in `parse.test.ts`, and asserting it here would say nothing about what
 * the decklist grammar can take.
 */
const READABLE = EXPORT_FORMATS.filter((f) => f !== "tcgplayer" && f !== "csv");

describe("what the mirror writes, the app can read", () => {
  const cards = corpus.scenarios.deck.cards;
  const copies = cards.reduce((n, c) => n + c.quantity, 0);

  it.each(READABLE)("parses the deck scenario back out of %s", (format) => {
    const parsed = parseDecklist(GOLDEN[`${DIR}/deck.${format}.all.txt`]);
    expect(parsed.issues).toEqual([]);
    expect(parsed.lines.length).toBeGreaterThan(0);
    for (const line of parsed.lines) expect(line.name).not.toBe("");
    // Every copy written comes back, and the only copies not written are the ones the format
    // itself leaves out — which is the number the dialog prints beside it.
    expect(parsed.totalCards).toBe(copies - omittedCount(cards, format));
  });
});
