import { describe, expect, it } from "vitest";
import manifest from "./src-tauri/gen/android/app/src/main/AndroidManifest.xml?raw";
import filePaths from "./src-tauri/gen/android/app/src/main/res/xml/file_paths.xml?raw";
import appGradle from "./src-tauri/gen/android/app/build.gradle.kts?raw";
import lightConf from "./src-tauri/tauri.conf.json?raw";
import lightCargo from "./src-tauri/Cargo.toml?raw";
import lightLib from "./src-tauri/src/lib.rs?raw";
import desktopConf from "../src-tauri/tauri.conf.json?raw";
import { HOST_MARK } from "@/lib/core";

/**
 * **The light host's hand edits, held.** `gen/android` is generated by `tauri android init` and
 * committed, and a re-init rewrites every file in it (the light-app spec §5) — so each edit made
 * by hand is a line here that goes red when a regeneration drops it, rather than a release that
 * quietly backs up `user.db` or shares external storage.
 */
describe("the Android project's hand edits", () => {
  it("never lets Android back up the databases", () => {
    // user.db restored onto a new phone carries the old device's sync identity: two devices that
    // each believe they are the same one. Sync is how a collection reaches another phone.
    expect(manifest).toMatch(/android:allowBackup="false"/);
    expect(manifest).toMatch(/android:fullBackupContent="false"/);
  });

  it("declares the camera, and does not require one", () => {
    expect(manifest).toMatch(/android\.permission\.CAMERA/);
    expect(manifest).toMatch(
      /<uses-feature android:name="android\.hardware\.camera" android:required="false"/,
    );
  });

  it("offers no TV launcher", () => {
    expect(manifest).not.toMatch(/LEANBACK/);
    expect(manifest).not.toMatch(/android\.software\.leanback/);
  });

  it("shares only cache/exports through the file provider", () => {
    expect(filePaths).not.toMatch(/external-path/);
    const paths = [...filePaths.matchAll(/<([a-z-]+-path)\b[^>]*>/g)].map((m) => m[0]);
    expect(paths).toEqual(['<cache-path name="exports" path="exports/" />']);
  });

  it("signs a release build with the debug key, until signing is decided", () => {
    const release = appGradle.slice(appGradle.indexOf('getByName("release")'));
    expect(release).toMatch(/signingConfig = signingConfigs\.getByName\("debug"\)/);
  });
});

describe("the light host's configuration", () => {
  const light = JSON.parse(lightConf) as {
    version: string;
    identifier: string;
    build: { frontendDist: string; devUrl: string };
    app: { security: { csp: string } };
    bundle: { android?: { minSdkVersion?: number } };
  };
  const desktop = JSON.parse(desktopConf) as {
    version: string;
    identifier: string;
    app: { security: { csp: string } };
  };

  it("ships from the desktop's tag, at the desktop's version", () => {
    // One core means one schema version: the three hosts ship from one tag (spec §7).
    expect(light.version).toBe(desktop.version);
    expect(lightCargo).toMatch(
      new RegExp(`^version = "${desktop.version.replace(/\./g, "\\.")}"`, "m"),
    );
  });

  it("is the same app id as the desktop, which Android needs as a Java package", () => {
    expect(light.identifier).toBe(desktop.identifier);
    expect(light.identifier).toMatch(/^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/);
  });

  it("serves the light bundle, and its dev server's port", () => {
    expect(light.build.frontendDist).toBe("../../dist-mobile");
    expect(light.build.devUrl).toBe("http://localhost:5175");
  });

  it("ships the desktop's CSP — the same IPC and image origins", () => {
    expect(light.app.security.csp).toBe(desktop.app.security.csp);
  });

  it("names API 26, the floor CI's NDK linker is built for", () => {
    expect(light.bundle.android?.minSdkVersion).toBe(26);
  });

  it("marks the page with the key src/lib/core reads", () => {
    // The two sides of the transport's one switch: the host sets it, the seam reads it.
    expect(lightLib).toContain(`window.${HOST_MARK} = \\"table\\";`);
  });

  it("never links the core's test scaffolding", () => {
    const core = lightCargo.split("\n").find((l) => l.startsWith("grimoire-core"));
    expect(core).toBeDefined();
    expect(core).not.toMatch(/testing/);
  });
});
