import { describe, expect, it } from "vitest";
import manifest from "./src-tauri/gen/android/app/src/main/AndroidManifest.xml?raw";
import filePaths from "./src-tauri/gen/android/app/src/main/res/xml/file_paths.xml?raw";
import appGradle from "./src-tauri/gen/android/app/build.gradle.kts?raw";
import mainActivity from "./src-tauri/gen/android/app/src/main/java/com/mtggrimoire/app/MainActivity.kt?raw";
import themes from "./src-tauri/gen/android/app/src/main/res/values/themes.xml?raw";
import nightThemes from "./src-tauri/gen/android/app/src/main/res/values-night/themes.xml?raw";
import colors from "./src-tauri/gen/android/app/src/main/res/values/colors.xml?raw";
import lightCapability from "./src-tauri/capabilities/light.json?raw";
import manifestJson from "./public/light.webmanifest?raw";
import lightMark from "./public/mtg-grimoire-mark.svg?raw";
import masterMark from "../logos/svg/mtg-grimoire-mark.svg?raw";
import lightDocument from "./index.html?raw";
import buildTask from "./src-tauri/gen/android/buildSrc/src/main/java/com/mtggrimoire/app/kotlin/BuildTask.kt?raw";
import packageJson from "../package.json?raw";
import lightConf from "./src-tauri/tauri.conf.json?raw";
import lightCargo from "./src-tauri/Cargo.toml?raw";
import lightLib from "./src-tauri/src/lib.rs?raw";
import desktopConf from "../src-tauri/tauri.conf.json?raw";
import { HOST_MARK } from "@/lib/core";

/**
 * **The light host's hand edits, held.** `gen/android` is generated by `tauri android init` and
 * committed, and a re-init rewrites every file in it (the light-app spec §5) — so each edit made
 * by hand is a line here that goes red when a regeneration drops it, rather than a release that
 * quietly backs up `user.db` or shares external storage.
 */
describe("the Android project's hand edits", () => {
  it("never lets Android back up the databases", () => {
    // user.db restored onto a new phone carries the old device's sync identity: two devices that
    // each believe they are the same one. Sync is how a collection reaches another phone.
    expect(manifest).toMatch(/android:allowBackup="false"/);
    expect(manifest).toMatch(/android:fullBackupContent="false"/);
  });

  it("declares the camera, and does not require one", () => {
    expect(manifest).toMatch(/android\.permission\.CAMERA/);
    expect(manifest).toMatch(
      /<uses-feature android:name="android\.hardware\.camera" android:required="false"/,
    );
  });

  it("offers no TV launcher", () => {
    expect(manifest).not.toMatch(/LEANBACK/);
    expect(manifest).not.toMatch(/android\.software\.leanback/);
  });

  it("shares only cache/exports through the file provider", () => {
    expect(filePaths).not.toMatch(/external-path/);
    const paths = [...filePaths.matchAll(/<([a-z-]+-path)\b[^>]*>/g)].map((m) => m[0]);
    expect(paths).toEqual(['<cache-path name="exports" path="exports/" />']);
  });

  it("has Gradle call the Tauri CLI from mobile/, where it finds this project", () => {
    // `npm run tauri` would start the CLI at the repository root, which finds the desktop's.
    expect(buildTask).toMatch(
      /listOf\("run", "--", "tauri:light", "android", "android-studio-script"\)/,
    );
    expect(JSON.parse(packageJson).scripts["tauri:light"]).toBe("cd mobile && tauri");
  });

  it("signs a release build with the debug key, until signing is decided", () => {
    const release = appGradle.slice(appGradle.indexOf('getByName("release")'));
    expect(release).toMatch(/signingConfig = signingConfigs\.getByName\("debug"\)/);
  });
});

describe("the Android window's insets", () => {
  it("keeps the page inside the bars, the cutout and the keyboard", () => {
    // targetSdk 35+ draws every app edge to edge and stops resizing it for the keyboard; the
    // content view's padding is what keeps a search box out from under the IME.
    expect(mainActivity).toMatch(/setOnApplyWindowInsetsListener/);
    for (const kind of ["systemBars()", "displayCutout()", "ime()"]) {
      expect(mainActivity).toContain(`WindowInsetsCompat.Type.${kind}`);
    }
  });

  it("draws light icons on both bars, the app being dark", () => {
    expect(mainActivity).toMatch(/statusBarStyle = SystemBarStyle\.dark/);
    expect(mainActivity).toMatch(/navigationBarStyle = SystemBarStyle\.dark/);
  });

  it("paints the ground behind the bars in the manifest's colour, by day and by night", () => {
    const ground = (JSON.parse(manifestJson) as { background_color: string }).background_color;
    expect(colors).toContain(`<color name="ground">#FF${ground.slice(1).toUpperCase()}</color>`);
    for (const theme of [themes, nightThemes]) {
      expect(theme).toContain('<item name="android:windowBackground">@color/ground</item>');
    }
  });
});

/**
 * **The web manifest, and where it lives.** It is the light app's alone — a browser installs the
 * web build from it, and Android's window takes its ground from it (above) — so it sits in
 * `mobile/public/`, the light builds' own public directory, with the icons it names. In the
 * `public/` at the repository root it was copied into the desktop's `dist/` and the share
 * viewer's `dist-share/` too.
 */
describe("the light app's web manifest", () => {
  interface Icon {
    src: string;
    sizes: string;
    type: string;
    purpose: string;
  }
  const manifest = JSON.parse(manifestJson) as {
    id: string;
    start_url: string;
    scope: string;
    display: string;
    background_color: string;
    theme_color: string;
    icons: Icon[];
  };
  /** Every file under a directory, by its path from the repository root. Keys only: nothing is
   *  loaded, so a picture costs the suite nothing. */
  const lightPublic = Object.keys(import.meta.glob("/mobile/public/**/*"));
  const sharedPublic = Object.keys(import.meta.glob("/public/**/*"));

  it("is one app at the origin's root, whatever page it was installed from", () => {
    // An `id` is what a browser knows an install by: without one it is the `start_url`, and a
    // later change to that would be a second app beside the first.
    expect(manifest.id).toBe("/");
    expect(manifest.start_url).toBe("/");
    expect(manifest.scope).toBe("/");
    expect(manifest.display).toBe("standalone");
  });

  it("names only icons that are in the light app's public directory", () => {
    expect(lightPublic).toContain("/mobile/public/light.webmanifest");
    for (const icon of manifest.icons) {
      expect(lightPublic, icon.src).toContain(`/mobile/public${icon.src}`);
    }
  });

  it("offers a raster icon at both sizes a browser asks for, and a maskable one", () => {
    const has = (purpose: string, sizes: string) =>
      manifest.icons.some(
        (icon) => icon.purpose === purpose && icon.sizes === sizes && icon.type === "image/png",
      );
    expect(has("any", "192x192")).toBe(true);
    expect(has("any", "512x512")).toBe(true);
    // Android cuts an installed icon to the launcher's shape; without a maskable one it shrinks
    // the transparent mark onto a white plate instead.
    expect(has("maskable", "512x512")).toBe(true);
    // One icon, one purpose: a single file declared `any maskable` is padded for one and wrong
    // for the other.
    for (const icon of manifest.icons) expect(icon.purpose).toMatch(/^(any|maskable)$/);
  });

  it("paints the page's chrome in the manifest's colour before a stylesheet loads", () => {
    expect(manifest.theme_color).toBe(manifest.background_color);
    expect(lightDocument).toContain(`<meta name="theme-color" content="${manifest.theme_color}" />`);
    expect(lightDocument).toContain('<link rel="manifest" href="/light.webmanifest" />');
  });

  it("is in no build but the light app's", () => {
    // `public/` is copied into the desktop's bundle and the share viewer's as it stands.
    expect(sharedPublic.length).toBeGreaterThan(0);
    expect(sharedPublic.filter((path) => /\.webmanifest$|\/icons\//.test(path))).toEqual([]);
  });

  it("serves the mark the desktop serves", () => {
    // Two public directories, so two copies of the favicon — and one master both must equal.
    expect(lightMark).toBe(masterMark);
  });
});

describe("Android's back gesture", () => {
  // The callback MainActivity adds, from `addCallback(` to the end of its `handleOnBackPressed`.
  const callback = (() => {
    const at = mainActivity.indexOf("onBackPressedDispatcher.addCallback(");
    return at < 0 ? "" : mainActivity.slice(at, mainActivity.indexOf("})", at));
  })();

  it("leaves the WebView's history to Tauri's AppPlugin", () => {
    // `AppPlugin` sends the gesture to `webView.goBack()` while the WebView can go back, and to the
    // activity only from the first entry; the phone router's pushes are those entries, so the
    // gesture closes a sheet. `TauriActivity` already turns wry's own handler off — turning the
    // plugin's off, or taking `onBackPressed` over its head, would be here.
    expect(mainActivity).not.toMatch(/handleBackNavigation/);
    expect(mainActivity).not.toMatch(/fun onBackPressed/);
  });

  it("puts the app away from the first page rather than finishing the activity", () => {
    // A finished activity ends Tauri's event loop, and tao's `std::process::exit` aborted on a
    // phone (`FORTIFY: pthread_mutex_lock called on a destroyed mutex`, 2026-10-04). The task goes
    // to the back instead, as Android 12+ does for a root launcher activity.
    expect(callback).toMatch(/OnBackPressedCallback\(true\)/);
    expect(callback).toMatch(/moveTaskToBack\(true\)/);
    expect(callback).not.toMatch(/finish/);
  });

  it("still walks the WebView's history, should its callback ever be asked first", () => {
    expect(mainActivity).toMatch(/override fun onWebViewCreate\(webView: WebView\)/);
    expect(callback).toMatch(/canGoBack\(\)/);
    expect(callback.indexOf("goBack()")).toBeLessThan(callback.indexOf("moveTaskToBack"));
  });

  it("is registered in onCreate, ahead of the plugin's, which waits for the WebView", () => {
    // The dispatcher asks the callback added last first, so registering here — before the WebView
    // exists, and so before `AppPlugin` is constructed — is what keeps history-back the plugin's.
    const onCreate = mainActivity.slice(mainActivity.indexOf("override fun onCreate("));
    expect(onCreate.indexOf("super.onCreate(")).toBeGreaterThan(-1);
    expect(onCreate.indexOf("onBackPressedDispatcher.addCallback(")).toBeGreaterThan(
      onCreate.indexOf("super.onCreate("),
    );
  });

  it("ends the process with _exit when the activity is destroyed any other way", () => {
    // tao's `EventLoop::run` would call `std::process::exit`, whose static destructors race the
    // framework's live threads; the host ends the process from `RunEvent::Exit` first.
    expect(lightLib).toMatch(/\.build\(tauri::generate_context!\(\)\)/);
    expect(lightLib).toMatch(/fn end_on_exit\(event: &tauri::RunEvent\)/);
    expect(lightLib).toMatch(/tauri::RunEvent::Exit/);
    expect(lightLib).toMatch(/libc::_exit\(0\)/);
    expect(lightCargo).toMatch(
      /\[target\.'cfg\(target_os = "android"\)'\.dependencies\][^[]*\blibc = /,
    );
  });
});

describe("the light host's capability", () => {
  it("grants core's defaults and the desktop's opener pair, and no dialog or fs permission", () => {
    // The opener pair is this host's way out to a browser for a press on either face
    // (`src/lib/core/host.ts`'s `tableHost`); dialog and fs are used from Rust only, so the page
    // is granted neither. No clipboard permission: the host has no such plugin, and the page
    // copies through `navigator.clipboard`.
    const cap = JSON.parse(lightCapability) as { permissions: string[] };
    expect(cap.permissions).toEqual([
      "core:default",
      "opener:allow-open-url",
      "opener:allow-default-urls",
    ]);
  });
});

describe("the light host's configuration", () => {
  const light = JSON.parse(lightConf) as {
    version: string;
    identifier: string;
    build: { frontendDist: string; devUrl: string };
    app: { security: { csp: string } };
    bundle: { android?: { minSdkVersion?: number } };
  };
  const desktop = JSON.parse(desktopConf) as {
    version: string;
    identifier: string;
    app: { security: { csp: string } };
  };

  it("ships from the desktop's tag, at the desktop's version", () => {
    // One core means one schema version: the three hosts ship from one tag (spec §7).
    expect(light.version).toBe(desktop.version);
    expect(lightCargo).toMatch(
      new RegExp(`^version = "${desktop.version.replace(/\./g, "\\.")}"`, "m"),
    );
  });

  it("is the same app id as the desktop, which Android needs as a Java package", () => {
    expect(light.identifier).toBe(desktop.identifier);
    expect(light.identifier).toMatch(/^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/);
  });

  it("serves the light bundle, and its dev server's port", () => {
    expect(light.build.frontendDist).toBe("../../dist-mobile");
    expect(light.build.devUrl).toBe("http://localhost:5175");
  });

  it("ships the desktop's CSP — the same IPC and image origins", () => {
    expect(light.app.security.csp).toBe(desktop.app.security.csp);
  });

  it("names API 26, the floor CI's NDK linker is built for", () => {
    expect(light.bundle.android?.minSdkVersion).toBe(26);
  });

  it("marks the page with the key src/lib/core reads", () => {
    // The two sides of the transport's one switch: the host sets it, the seam reads it.
    expect(lightLib).toContain(`window.${HOST_MARK} = \\"table\\";`);
  });

  it("never links the core's test scaffolding", () => {
    const core = lightCargo.split("\n").find((l) => l.startsWith("grimoire-core"));
    expect(core).toBeDefined();
    expect(core).not.toMatch(/testing/);
  });
});
