/**
 * Release notes, read into something the app can draw.
 *
 * **This is a reader for release-please's output, not a markdown parser**, and the narrow
 * name is the honest one. Every release body this app will ever show is generated by
 * `release-please` from conventional commits, so the vocabulary is closed and knowable:
 * a version heading, `### Features` / `### Bug Fixes`, bullets carrying `**scope:**` and a
 * commit trailer, and the occasional hand-written paragraph under
 * `### ⚠ BREAKING CHANGES`. That is the whole of it, and it is the reason a 150-line
 * reader is preferable here to a dependency — the shipped CSP is `script-src 'self'` with
 * **no `dangerouslySetInnerHTML` anywhere in `src/`**, so a library that answers an HTML
 * string could not be used at all, and one that answers elements would drag micromark in to
 * parse four shapes.
 *
 * **Nothing is ever dropped for not being understood.** A line this file has no rule for
 * falls through to a paragraph and is rendered as written, which is what keeps the panel
 * from half-rendering a body somebody wrote by hand. The old panel's argument — that
 * unrendered markdown beats half-rendered markdown — is answered by the fallback, not
 * abandoned.
 *
 * Rust stores the body verbatim (`update::ReleaseInfo::notes`) and concludes nothing about
 * it. The three display decisions are all here:
 *
 * - the **leading version heading** is dropped, because the row it is drawn under already
 *   says the version and the date;
 * - the **commit trailer** is stripped, because a reader of a desktop changelog can do
 *   nothing with a SHA;
 * - **identical bullets collapse**, because the same message landing on two branches is one
 *   fact and release-please writes it twice.
 *
 * The renderer is `src/features/settings/ReleaseNotes.tsx`.
 */

/** A run of text inside a block. */
export type Inline =
  | { kind: "text"; text: string }
  | { kind: "strong"; text: string }
  | { kind: "code"; text: string }
  | { kind: "link"; text: string; href: string };

/** One drawable block. Three kinds, because release-please emits three. */
export type Block =
  | { kind: "heading"; level: 1 | 2 | 3; inlines: Inline[] }
  | { kind: "list"; items: Inline[][] }
  | { kind: "paragraph"; inlines: Inline[] };

/**
 * release-please's provenance trailer: `([23d15d5](https://github.com/…/commit/23d15d5d…))`.
 *
 * **Narrow on purpose, at both ends.** The link text must be a hex abbreviation *and* the
 * href must be a github.com commit URL, so an ordinary link in a hand-written body — the
 * research doc, an issue, a Scryfall page — is content and survives. A looser rule here
 * would silently eat the one kind of link a release note is written to carry.
 */
const COMMIT_TRAILER = /\s*\(\[[0-9a-f]{6,40}\]\(https:\/\/github\.com\/\S*?\/commit\/[0-9a-f]{6,40}\)\)/gi;

/** `## Heading`, at any of the six depths markdown allows. */
const HEADING = /^(#{1,6})\s+(.*)$/;

/**
 * A bullet, either marker, indented or not.
 *
 * `\s+` after the marker is what keeps `**decks:** …` from reading as one: a `*` followed by
 * another `*` is not a list. Nesting is flattened — release-please emits none, and a nested
 * bullet in a hand-written body reads perfectly well one level up.
 */
const BULLET = /^\s*[*-]\s+(.*)$/;

/** Bold, inline code, and a link — scanned left to right in one pass. */
const INLINE = /\*\*([\s\S]+?)\*\*|`([^`]+)`|\[([^\]]+)\]\(([^()\s]+)\)/g;

/** A heading that is only a version and a date, which is what a release body opens with. */
const VERSION_HEADING = /^v?\d+\.\d+\.\d+\b/;

/**
 * Only `https:` becomes an anchor. Everything else keeps its words and loses its link.
 *
 * A release body is text off the network, and `[click me](javascript:…)` is the oldest trick
 * in the book. `update_open_release_page` applies the same kind of fence in Rust before
 * handing a URL to the opener; this is the webview's end of it, and the reason a refused URL
 * degrades to plain text rather than disappearing is that the sentence around it is still
 * worth reading.
 */
function isOpenable(href: string): boolean {
  return href.toLowerCase().startsWith("https://");
}

/**
 * The five named entities a release body actually carries.
 *
 * **Not decoration — release-please escapes angle brackets**, and this repo's own v0.8.0
 * changelog carries the same commit message twice, once as `` `<select>` `` and once as
 * `\&lt;select&gt;\`, because it landed on two branches and one went through the escaper.
 * Undecoded, the second reads as five literal characters in a shipped window.
 *
 * A table of five rather than a general numeric-entity decoder: these are what markdown's
 * own escaping produces, and a decoder that turned `&#60;` into `<` would be inventing a
 * capability for text nobody writes. Anything else stays as written, which is this file's
 * rule everywhere.
 */
const ENTITIES: Record<string, string> = {
  "&lt;": "<",
  "&gt;": ">",
  "&quot;": '"',
  "&#39;": "'",
  "&amp;": "&",
};

/**
 * One left-to-right pass, which is what makes `&amp;lt;` come out as the literal `&lt;` its
 * author meant rather than as `<`: the scanner consumes `&amp;`, emits `&`, and resumes
 * *after* it, so the `lt;` behind is never re-read as the tail of a second entity.
 */
function decodeEntities(text: string): string {
  return text.replace(/&(?:lt|gt|quot|amp|#39);/g, (m) => ENTITIES[m] ?? m);
}

/**
 * Split one line into its runs. Adjacent text runs are left unmerged — nothing needs it.
 *
 * Entities are decoded everywhere **except inside a code span**, which is CommonMark's own
 * rule and the one that matters here: `` `&lt;` `` is a reader being shown the escape, and
 * decoding it would silently rewrite what a note says.
 */
function parseInlines(line: string): Inline[] {
  const out: Inline[] = [];
  let at = 0;
  INLINE.lastIndex = 0;
  let m: RegExpExecArray | null;
  while ((m = INLINE.exec(line)) !== null) {
    if (m.index > at) out.push({ kind: "text", text: decodeEntities(line.slice(at, m.index)) });
    const [, strong, code, linkText, href] = m;
    if (strong !== undefined) out.push({ kind: "strong", text: decodeEntities(strong) });
    else if (code !== undefined) out.push({ kind: "code", text: code });
    else if (linkText !== undefined && href !== undefined) {
      const text = decodeEntities(linkText);
      out.push(isOpenable(href) ? { kind: "link", text, href } : { kind: "text", text });
    }
    at = m.index + m[0].length;
  }
  if (at < line.length) out.push({ kind: "text", text: decodeEntities(line.slice(at)) });
  return out;
}

/** Everything a block says, with the markup gone — for dedup, and for tests. */
export function plainText(node: Block | Inline[]): string {
  if (Array.isArray(node)) return node.map((i) => i.text).join("");
  if (node.kind === "list") return node.items.map(plainText).join("\n");
  return plainText(node.inlines);
}

/**
 * Close off the paragraph being accumulated, if there is one.
 *
 * Consecutive plain lines join with a space rather than a newline: they are one wrapped
 * sentence in the source, and a `<p>` is where wrapping is decided.
 */
function flush(lines: string[], out: Block[]): void {
  const text = lines.join(" ").trim();
  lines.length = 0;
  if (text) out.push({ kind: "paragraph", inlines: parseInlines(text) });
}

/**
 * Close off the bullets being accumulated, collapsing the ones that say the same thing.
 *
 * **Per list rather than per body**, because two sections legitimately mention the same
 * change from two angles, while a repeat inside one section is release-please writing one
 * fact twice. It runs after the trailer has been stripped, which is the whole mechanism:
 * two bullets that differed only by SHA are not identical until then.
 */
function flushItems(items: Inline[][], out: Block[]): void {
  const seen = new Set<string>();
  const kept = items.filter((item) => {
    const key = plainText(item).trim();
    if (!key || seen.has(key)) return false;
    seen.add(key);
    return true;
  });
  items.length = 0;
  if (kept.length) out.push({ kind: "list", items: kept });
}

/**
 * Take the commit trailer off one line's **content**.
 *
 * Applied after the line's shape has been recognised rather than to the whole body first,
 * and the difference is a real one: the trailer's leading `\s*` eats the space after the
 * bullet marker, so a document-wide strip turns `* ([23d15d5](…))` into a bare `*` — a line
 * that is no longer a bullet and renders as a stray asterisk in a paragraph.
 */
function strip(text: string): string {
  return text.replace(COMMIT_TRAILER, "").trim();
}

/**
 * A release body → blocks, ready to draw. An empty body answers an empty list.
 *
 * @param notes the release body as GitHub served it, markdown and all.
 */
export function parseReleaseNotes(notes: string): Block[] {
  const out: Block[] = [];
  const paragraph: string[] = [];
  const items: Inline[][] = [];

  for (const raw of notes.split("\n")) {
    const line = raw.trimEnd();

    if (!line.trim()) {
      flushItems(items, out);
      flush(paragraph, out);
      continue;
    }

    const heading = HEADING.exec(line);
    if (heading) {
      flushItems(items, out);
      flush(paragraph, out);
      const level = Math.min(3, heading[1].length) as 1 | 2 | 3;
      out.push({ kind: "heading", level, inlines: parseInlines(strip(heading[2])) });
      continue;
    }

    const bullet = BULLET.exec(line);
    if (bullet) {
      flush(paragraph, out);
      // A bullet whose whole content was its trailer is not a bullet. `flushItems` would
      // drop it anyway on the empty key, but not adding it keeps that rule about *repeats*.
      const content = strip(bullet[1]);
      if (content) items.push(parseInlines(content));
      continue;
    }

    flushItems(items, out);
    const content = strip(line);
    if (content) paragraph.push(content);
  }
  flushItems(items, out);
  flush(paragraph, out);

  // The version heading, and only the leading one: further down it is a section somebody
  // wrote, and this app is not entitled to decide that a heading in the middle of a body is
  // redundant.
  const first = out[0];
  if (first?.kind === "heading" && VERSION_HEADING.test(plainText(first))) out.shift();
  return out;
}
