import { describe, expect, it } from "vitest";
import manifest from "./src-tauri/gen/android/app/src/main/AndroidManifest.xml?raw";
import filePaths from "./src-tauri/gen/android/app/src/main/res/xml/file_paths.xml?raw";
import appGradle from "./src-tauri/gen/android/app/build.gradle.kts?raw";
import androidIgnore from "./src-tauri/gen/android/.gitignore?raw";
import signScript from "../../scripts/android-release/sign-bundle.sh?raw";
import releaseYml from "../../.github/workflows/release.yml?raw";
import mainActivity from "./src-tauri/gen/android/app/src/main/java/com/mtggrimoire/app/MainActivity.kt?raw";
import themes from "./src-tauri/gen/android/app/src/main/res/values/themes.xml?raw";
import nightThemes from "./src-tauri/gen/android/app/src/main/res/values-night/themes.xml?raw";
import colors from "./src-tauri/gen/android/app/src/main/res/values/colors.xml?raw";
import lightCapability from "./src-tauri/capabilities/light.json?raw";
import manifestJson from "./public/light.webmanifest?raw";
import lightMark from "./public/mtg-grimoire-mark.svg?raw";
import masterMark from "../../logos/svg/mtg-grimoire-mark.svg?raw";
import lightDocument from "./index.html?raw";
import iconScript from "../../scripts/light-icons.mjs?raw";
import buildTask from "./src-tauri/gen/android/buildSrc/src/main/java/com/mtggrimoire/app/kotlin/BuildTask.kt?raw";
import packageJson from "../../package.json?raw";
import lightConf from "./src-tauri/tauri.conf.json?raw";
import lightCargo from "./src-tauri/Cargo.toml?raw";
import workspaceCargo from "../../Cargo.toml?raw";
import lightLib from "./src-tauri/src/lib.rs?raw";
import lightMembership from "./src-tauri/src/membership.rs?raw";
import coreCommands from "../../crates/grimoire-core/src/commands.rs?raw";
import coreSyncClient from "../../crates/grimoire-core/src/sync_engine/client.rs?raw";
import desktopConf from "../desktop/src-tauri/tauri.conf.json?raw";
import adaptiveIcon from "./src-tauri/gen/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml?raw";
import privacyPage from "./public/privacy.html?raw";
import privacySheet from "./public/privacy.css?raw";
import hostHeaders from "../../infrastructure/app-worker/_headers?raw";
import { HOST_MARK } from "@/lib/core";
import { MEMBERSHIP_ELSEWHERE } from "@/lib/core/hostMembership";

/** The launcher's pictures as data URLs — small files, and a PNG's size is in its first bytes. */
const launcherPngs = import.meta.glob(
  "./src-tauri/gen/android/app/src/main/res/mipmap-*/*.png",
  { query: "?inline", import: "default", eager: true },
) as Record<string, string>;
const launcherFiles = Object.keys(
  import.meta.glob("./src-tauri/gen/android/app/src/main/res/{mipmap,drawable}*/*"),
);

/** A PNG's width and height: big-endian, at bytes 16 and 20 of its header. */
function pngSize(dataUrl: string): { width: number; height: number } {
  const bytes = Uint8Array.from(atob(dataUrl.slice(dataUrl.indexOf(",") + 1)), (c) =>
    c.charCodeAt(0),
  );
  const view = new DataView(bytes.buffer);
  return { width: view.getUint32(16), height: view.getUint32(20) };
}

/**
 * **The light host's hand edits, held.** `gen/android` is generated by `tauri android init` and
 * committed, and a re-init rewrites every file in it (the light-app spec §5) — so each edit made
 * by hand is a line here that goes red when a regeneration drops it, rather than a release that
 * quietly backs up `user.db` or shares external storage.
 */
describe("the Android project's hand edits", () => {
  it("never lets Android back up the databases", () => {
    // user.db restored onto a new phone carries the old device's sync identity: two devices that
    // each believe they are the same one. Sync is how a collection reaches another phone.
    expect(manifest).toMatch(/android:allowBackup="false"/);
    expect(manifest).toMatch(/android:fullBackupContent="false"/);
  });

  it("declares the camera, and does not require one", () => {
    expect(manifest).toMatch(/android\.permission\.CAMERA/);
    expect(manifest).toMatch(
      /<uses-feature android:name="android\.hardware\.camera" android:required="false"/,
    );
  });

  it("offers no TV launcher", () => {
    expect(manifest).not.toMatch(/LEANBACK/);
    expect(manifest).not.toMatch(/android\.software\.leanback/);
  });

  it("shares only cache/exports through the file provider", () => {
    expect(filePaths).not.toMatch(/external-path/);
    const paths = [...filePaths.matchAll(/<([a-z-]+-path)\b[^>]*>/g)].map((m) => m[0]);
    expect(paths).toEqual(['<cache-path name="exports" path="exports/" />']);
  });

  it("has Gradle call the Tauri CLI from apps/light/, where it finds this project", () => {
    // `npm run tauri` would start the CLI at the repository root, which finds the desktop's.
    expect(buildTask).toMatch(
      /listOf\("run", "--", "tauri:light", "android", "android-studio-script"\)/,
    );
    expect(JSON.parse(packageJson).scripts["tauri:light"]).toBe("cd apps/light && tauri");
  });

  it("signs a release build with the debug key, and knows no other", () => {
    // The upload key is `release.yml`'s `android-sign` job's, which re-signs the bundle this
    // project built (`scripts/android-release/sign-bundle.sh`) and runs no build. A signing
    // config here would put the keystore and its passwords on disk beside every npm script,
    // cargo build script and Gradle plugin a build runs.
    const release = appGradle.slice(appGradle.indexOf('getByName("release")'));
    expect(release).toMatch(/signingConfig = signingConfigs\.getByName\("debug"\)/);
    const code = appGradle
      .split("\n")
      .filter((line) => !line.trim().startsWith("//"))
      .join("\n");
    expect(code).not.toMatch(/signingConfigs\s*\{|storeFile|storePassword|keyPassword|keyAlias/);
    expect(code).not.toMatch(/keystore/i);
  });

  it("ignores a keystore, should one ever be put beside the project", () => {
    for (const name of ["keystore.properties", "key.properties", "*.jks", "*.keystore"]) {
      expect(androidIgnore.split(/\r?\n/), name).toContain(name);
    }
  });

  it("names the release's signer in one line of hex, once the owner has made the key", () => {
    // `src-tauri/release-signer.sha256` is the SHA-256 of the upload certificate every release's
    // bundle is signed with — public, and what Play Console shows as the upload key. `release.yml`
    // signs no bundle until it is committed, and `scripts/android-release/sign-bundle.sh` refuses
    // a keystore that is not the one it names. **Absent until the key exists**, so this holds
    // its shape for the day it appears — the script reads it with the same rule, and a file it
    // cannot read is a release with no bundle to upload.
    const pins = Object.entries(
      import.meta.glob("./src-tauri/release-signer.sha256", {
        query: "?raw",
        import: "default",
        eager: true,
      }),
    ) as [string, string][];
    expect(pins.length).toBeLessThanOrEqual(1);
    for (const [, pin] of pins) expect(pin).toMatch(/^[0-9a-f]{64}\n$/);
    // The script's own reading of it, so the two rules cannot part.
    expect(signScript).toContain('[[ "$pin" =~ ^[0-9a-f]{64}$ ]]');
    expect(releaseYml).toContain("ANDROID_SIGNER_PIN: apps/light/src-tauri/release-signer.sha256");
  });

  it("holds no keystore and no signing properties", () => {
    // Keys only — nothing is loaded. A file a `.gitignore` hides is found too, on purpose: a
    // key in this tree is one `git add -f` from a public repository.
    const keys = Object.keys(
      import.meta.glob([
        "/apps/light/**/*.{jks,keystore,p12,pfx}",
        "/apps/light/**/{keystore,key,signing}.properties",
        "/*.{jks,keystore,p12,pfx}",
        "!**/node_modules/**",
        "!**/build/**",
      ]),
    );
    expect(keys).toEqual([]);
  });
});

describe("the Android window's insets", () => {
  it("keeps the page inside the bars, the cutout and the keyboard", () => {
    // targetSdk 35+ draws every app edge to edge and stops resizing it for the keyboard; the
    // content view's padding is what keeps a search box out from under the IME.
    expect(mainActivity).toMatch(/setOnApplyWindowInsetsListener/);
    for (const kind of ["systemBars()", "displayCutout()", "ime()"]) {
      expect(mainActivity).toContain(`WindowInsetsCompat.Type.${kind}`);
    }
  });

  it("draws light icons on both bars, the app being dark", () => {
    expect(mainActivity).toMatch(/statusBarStyle = SystemBarStyle\.dark/);
    expect(mainActivity).toMatch(/navigationBarStyle = SystemBarStyle\.dark/);
  });

  it("paints the ground behind the bars in the manifest's colour, by day and by night", () => {
    const ground = (JSON.parse(manifestJson) as { background_color: string }).background_color;
    expect(colors).toContain(`<color name="ground">#FF${ground.slice(1).toUpperCase()}</color>`);
    for (const theme of [themes, nightThemes]) {
      expect(theme).toContain('<item name="android:windowBackground">@color/ground</item>');
    }
  });
});

/**
 * **The web manifest, and where it lives.** It is the light app's alone — a browser installs the
 * web build from it, and Android's window takes its ground from it (above) — so it sits in
 * `apps/light/public/`, the light builds' own public directory, with the icons it names. In the
 * `public/` at the repository root it was copied into the desktop's `dist/` and the share
 * viewer's `apps/share/dist-share/` too.
 */
describe("the light app's web manifest", () => {
  interface Icon {
    src: string;
    sizes: string;
    type: string;
    purpose: string;
  }
  const manifest = JSON.parse(manifestJson) as {
    id: string;
    start_url: string;
    scope: string;
    display: string;
    background_color: string;
    theme_color: string;
    icons: Icon[];
  };
  /** Every file under a directory, by its path from the repository root. Keys only: nothing is
   *  loaded, so a picture costs the suite nothing. */
  const lightPublic = Object.keys(import.meta.glob("/apps/light/public/**/*"));
  const sharedPublic = Object.keys(import.meta.glob("/apps/desktop/public/**/*"));

  it("is one app at the origin's root, whatever page it was installed from", () => {
    // An `id` is what a browser knows an install by: without one it is the `start_url`, and a
    // later change to that would be a second app beside the first.
    expect(manifest.id).toBe("/");
    expect(manifest.start_url).toBe("/");
    expect(manifest.scope).toBe("/");
    expect(manifest.display).toBe("standalone");
  });

  it("names only icons that are in the light app's public directory", () => {
    expect(lightPublic).toContain("/apps/light/public/light.webmanifest");
    for (const icon of manifest.icons) {
      expect(lightPublic, icon.src).toContain(`/apps/light/public${icon.src}`);
    }
  });

  it("offers a raster icon at both sizes a browser asks for, and a maskable one", () => {
    const has = (purpose: string, sizes: string) =>
      manifest.icons.some(
        (icon) => icon.purpose === purpose && icon.sizes === sizes && icon.type === "image/png",
      );
    expect(has("any", "192x192")).toBe(true);
    expect(has("any", "512x512")).toBe(true);
    // Android cuts an installed icon to the launcher's shape; without a maskable one it shrinks
    // the transparent mark onto a white plate instead.
    expect(has("maskable", "512x512")).toBe(true);
    // One icon, one purpose: a single file declared `any maskable` is padded for one and wrong
    // for the other.
    for (const icon of manifest.icons) expect(icon.purpose).toMatch(/^(any|maskable)$/);
  });

  it("paints the page's chrome in the manifest's colour before a stylesheet loads", () => {
    expect(manifest.theme_color).toBe(manifest.background_color);
    expect(lightDocument).toContain(`<meta name="theme-color" content="${manifest.theme_color}" />`);
    expect(lightDocument).toContain('<link rel="manifest" href="/light.webmanifest" />');
  });

  it("is in no build but the light app's", () => {
    // `public/` is copied into the desktop's bundle and the share viewer's as it stands.
    expect(sharedPublic.length).toBeGreaterThan(0);
    expect(sharedPublic.filter((path) => /\.webmanifest$|\/icons\//.test(path))).toEqual([]);
  });

  it("draws the maskable icons on the manifest's ground", () => {
    // The PNGs are rendered and committed (`scripts/light-icons.mjs`), so the colour under the
    // mark is that script's constant. Held here so a ground that moves is rendered again.
    expect(iconScript).toContain(`const GROUND = "${manifest.background_color}";`);
    expect(manifest.background_color).toMatch(/^#[0-9A-F]{6}$/);
  });

  it("serves the mark the desktop serves", () => {
    // Two public directories, so two copies of the favicon — and one master both must equal.
    expect(lightMark).toBe(masterMark);
  });
});

describe("Android's back gesture", () => {
  // The callback MainActivity adds, from `addCallback(` to the end of its `handleOnBackPressed`.
  const callback = (() => {
    const at = mainActivity.indexOf("onBackPressedDispatcher.addCallback(");
    return at < 0 ? "" : mainActivity.slice(at, mainActivity.indexOf("})", at));
  })();

  it("leaves the WebView's history to Tauri's AppPlugin", () => {
    // `AppPlugin` sends the gesture to `webView.goBack()` while the WebView can go back, and to the
    // activity only from the first entry; the phone router's pushes are those entries, so the
    // gesture closes a sheet. `TauriActivity` already turns wry's own handler off — turning the
    // plugin's off, or taking `onBackPressed` over its head, would be here.
    expect(mainActivity).not.toMatch(/handleBackNavigation/);
    expect(mainActivity).not.toMatch(/fun onBackPressed/);
  });

  it("puts the app away from the first page rather than finishing the activity", () => {
    // A finished activity ends Tauri's event loop, and tao's `std::process::exit` aborted on a
    // phone (`FORTIFY: pthread_mutex_lock called on a destroyed mutex`, 2026-10-04). The task goes
    // to the back instead, as Android 12+ does for a root launcher activity.
    expect(callback).toMatch(/OnBackPressedCallback\(true\)/);
    expect(callback).toMatch(/moveTaskToBack\(true\)/);
    expect(callback).not.toMatch(/finish/);
  });

  it("still walks the WebView's history, should its callback ever be asked first", () => {
    expect(mainActivity).toMatch(/override fun onWebViewCreate\(webView: WebView\)/);
    expect(callback).toMatch(/canGoBack\(\)/);
    expect(callback.indexOf("goBack()")).toBeLessThan(callback.indexOf("moveTaskToBack"));
  });

  it("is registered in onCreate, ahead of the plugin's, which waits for the WebView", () => {
    // The dispatcher asks the callback added last first, so registering here — before the WebView
    // exists, and so before `AppPlugin` is constructed — is what keeps history-back the plugin's.
    const onCreate = mainActivity.slice(mainActivity.indexOf("override fun onCreate("));
    expect(onCreate.indexOf("super.onCreate(")).toBeGreaterThan(-1);
    expect(onCreate.indexOf("onBackPressedDispatcher.addCallback(")).toBeGreaterThan(
      onCreate.indexOf("super.onCreate("),
    );
  });

  it("ends the process with _exit when the activity is destroyed any other way", () => {
    // tao's `EventLoop::run` would call `std::process::exit`, whose static destructors race the
    // framework's live threads; the host ends the process from `RunEvent::Exit` first.
    expect(lightLib).toMatch(/\.build\(tauri::generate_context!\(\)\)/);
    expect(lightLib).toMatch(/fn end_on_exit\(event: &tauri::RunEvent\)/);
    expect(lightLib).toMatch(/tauri::RunEvent::Exit/);
    expect(lightLib).toMatch(/libc::_exit\(0\)/);
    expect(lightCargo).toMatch(
      /\[target\.'cfg\(target_os = "android"\)'\.dependencies\][^[]*\blibc = /,
    );
  });
});

describe("the light host's capability", () => {
  it("grants core's defaults and the desktop's opener pair, and no dialog or fs permission", () => {
    // The opener pair is this host's way out to a browser for a press on either face
    // (`packages/ui/lib/core/host.ts`'s `tableHost`); dialog and fs are used from Rust only, so the page
    // is granted neither. No clipboard permission: the host has no such plugin, and the page
    // copies through `navigator.clipboard`.
    const cap = JSON.parse(lightCapability) as { permissions: string[] };
    expect(cap.permissions).toEqual([
      "core:default",
      "opener:allow-open-url",
      "opener:allow-default-urls",
    ]);
  });
});

describe("the light host's configuration", () => {
  const light = JSON.parse(lightConf) as {
    version: string;
    identifier: string;
    build: { frontendDist: string; devUrl: string };
    app: { security: { csp: string } };
    bundle: { android?: { minSdkVersion?: number } };
  };
  const desktop = JSON.parse(desktopConf) as {
    version: string;
    identifier: string;
    app: { security: { csp: string } };
  };

  it("ships from the desktop's tag, at the desktop's version", () => {
    // One core means one schema version: the three hosts ship from one tag (spec §7).
    expect(light.version).toBe(desktop.version);
    // The crate's own version has been the workspace's since 2026-10-08, and the workspace's is the
    // one release-please writes: so the crate says what the desktop says by inheriting, and the
    // root manifest carries the desktop's number.
    expect(lightCargo).toMatch(/^version\.workspace = true$/m);
    expect(workspaceCargo).toMatch(
      new RegExp(`^\\[workspace\\.package\\]\\s*\\nversion = "${desktop.version.replace(/\./g, "\\.")}"`, "m"),
    );
  });

  it("is the same app id as the desktop, which Android needs as a Java package", () => {
    expect(light.identifier).toBe(desktop.identifier);
    expect(light.identifier).toMatch(/^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/);
  });

  it("serves the light bundle, and its dev server's port", () => {
    expect(light.build.frontendDist).toBe("../dist-mobile");
    expect(light.build.devUrl).toBe("http://localhost:5175");
  });

  it("ships the desktop's CSP — the same IPC and image origins", () => {
    expect(light.app.security.csp).toBe(desktop.app.security.csp);
  });

  it("names API 26, the floor CI's NDK linker is built for", () => {
    expect(light.bundle.android?.minSdkVersion).toBe(26);
  });

  it("marks the page with the key packages/ui/lib/core reads", () => {
    // The two sides of the transport's one switch: the host sets it, the seam reads it.
    expect(lightLib).toContain(`window.${HOST_MARK} = \\"table\\";`);
  });

  it("never links the core's test scaffolding", () => {
    const core = lightCargo.split("\n").find((l) => l.startsWith("grimoire-core"));
    expect(core).toBeDefined();
    expect(core).not.toMatch(/testing/);
  });
});

/**
 * **The launcher's icon is the app's own mark.** `tauri android init` writes Tauri's logo into
 * every `mipmap-*` and Android's stock robot into `drawable*`, and the app shipped to a phone
 * that way until 2026-10-07. `scripts/light-icons.mjs` renders these from the master mark and
 * they are committed; a regeneration puts the stock art back, and this is what goes red.
 */
describe("the Android launcher icon", () => {
  const DENSITIES = { mdpi: 1, hdpi: 1.5, xhdpi: 2, xxhdpi: 3, xxxhdpi: 4 };
  const at = (density: string, file: string) =>
    launcherPngs[`./src-tauri/gen/android/app/src/main/res/mipmap-${density}/${file}`];

  it.each(Object.entries(DENSITIES))("is drawn at %s: 48dp, and a 108dp layer", (density, scale) => {
    expect(pngSize(at(density, "ic_launcher.png"))).toEqual({
      width: 48 * scale,
      height: 48 * scale,
    });
    expect(pngSize(at(density, "ic_launcher_foreground.png"))).toEqual({
      width: 108 * scale,
      height: 108 * scale,
    });
  });

  it("is adaptive: the app's ground behind, the mark in front", () => {
    expect(adaptiveIcon).toContain('<background android:drawable="@color/ground" />');
    expect(adaptiveIcon).toContain('<foreground android:drawable="@mipmap/ic_launcher_foreground" />');
    // The manifest asks for `@mipmap/ic_launcher`; on every phone this app installs on
    // (minSdk 26) that name is this file.
    expect(manifest).toMatch(/android:icon="@mipmap\/ic_launcher"/);
    expect(manifest).not.toMatch(/android:roundIcon/);
  });

  it("holds none of the stock art `tauri android init` leaves", () => {
    const names = launcherFiles.map((path) => path.slice(path.indexOf("/res/") + 5)).sort();
    expect(names).toEqual(
      [
        "mipmap-anydpi-v26/ic_launcher.xml",
        ...Object.keys(DENSITIES).flatMap((density) => [
          `mipmap-${density}/ic_launcher.png`,
          `mipmap-${density}/ic_launcher_foreground.png`,
        ]),
      ].sort(),
    );
  });

  it("is rendered inside the circle a launcher may cut it to", () => {
    // The script measures the pixels and fails the render; this holds the rule it measures by.
    expect(iconScript).toContain("const ADAPTIVE_SAFE_RADIUS = 33 / 108;");
    expect(iconScript).toMatch(/const ADAPTIVE_SCALE = 0\.\d+;/);
  });
});

/**
 * **The privacy policy** — `https://mtg-grimoire.app/privacy`, which Google Play's listing and
 * the app's Settings both link to. A document, not the app: it must read under the host's
 * policy with no script at all, and it must not fall behind the list of hosts the app asks.
 */
describe("the privacy policy's page", () => {
  it("runs no script and carries no style of its own", () => {
    // `script-src 'self' 'wasm-unsafe-eval'; style-src 'self'` — and a policy that needs
    // neither cannot be broken by either.
    expect(privacyPage).not.toMatch(/<script\b/i);
    expect(privacyPage).not.toMatch(/<style\b/i);
    expect(privacyPage).not.toMatch(/\sstyle=/i);
    expect(privacyPage).not.toMatch(/\son[a-z]+=/i);
    expect(privacyPage).toContain('<link rel="stylesheet" href="/privacy.css" />');
    expect(privacySheet).not.toMatch(/@import|url\(/);
  });

  it("is a whole document with one heading", () => {
    expect(privacyPage).toMatch(/^<!doctype html>\n<html lang="en">/);
    expect(privacyPage.match(/<h1>/g)).toHaveLength(1);
    expect(privacyPage).toMatch(/<h1>MTG Grimoire privacy policy<\/h1>/);
    expect(privacyPage).toMatch(/Effective \d{1,2} [A-Z][a-z]+ 20\d\d\./);
  });

  it("names every host the app's own policy lets it ask", () => {
    // The web host's `connect-src` is the engine's list of hosts, held to the engine's
    // constants by `infrastructure/app-worker/src/hosting.test.ts`. A host added there is a host this page
    // owes a line.
    const policy = /Content-Security-Policy:.*connect-src ([^;]+);/.exec(hostHeaders)?.[1] ?? "";
    const hosts = [...new Set([...policy.matchAll(/(?:https|wss):\/\/([a-z0-9.-]+)/g)].map((m) => m[1]))];
    expect(hosts.length).toBeGreaterThanOrEqual(6);
    for (const host of hosts) expect(privacyPage, host).toContain(`<td>${host}</td>`);
    // And the two the Android host asks that a browser may not: Mana Pool's price list, and
    // GitHub for the scanner's files (`scanner_assets::RELEASES`, a reader's press — step 7.4).
    expect(privacyPage).toContain("<td>manapool.com</td>");
    expect(privacyPage).toContain("<td>github.com</td>");
  });

  it("offers nothing to pay for", () => {
    // It says what a membership stores; it never says how to get one.
    expect(privacyPage).not.toMatch(/patreon\.com|\$\s?\d|€\s?\d|per month|subscribe|join now|become a|funded|paid for/i);
  });
});

/**
 * **The build Google Play distributes offers no membership** (2026-10-07). Play forbids an app
 * to lead a reader to a payment made elsewhere, so this host answers one name with a sentence
 * of its own, refuses the two commands that connect a membership, and rewords the core's
 * sentences that tell a reader to. Each of the three is a thing a careless edit can drop, and
 * a dropped one is a policy strike found by a reviewer and not by a test.
 */
describe("the light host offers no membership", () => {
  const literal = (name: string) =>
    new RegExp(`pub const ${name}: &str =\\s*"([^"\\\\]+)";`).exec(lightMembership)?.[1];

  /** `forward`'s body: `core_call`'s tail, and this host's one call into the core's table. */
  const forwardBody = () => {
    const from = lightLib.indexOf("async fn forward(");
    expect(from).toBeGreaterThan(-1);
    const rest = lightLib.slice(from);
    return rest.slice(0, rest.indexOf("\n}\n"));
  };

  it("answers the name the page asks by", () => {
    expect(literal("ELSEWHERE")).toBe(MEMBERSHIP_ELSEWHERE);
    // One line, which is how the Storybook fake reads it.
    expect(literal("SENTENCE")).toMatch(/paired/);
  });

  it("is asked before the core's table, and rewords what the table refuses", () => {
    const call = lightLib.slice(lightLib.indexOf("async fn core_call("));
    const body = call.slice(0, call.indexOf("\n}\n"));
    expect(body).toContain("if membership::answers(&name) {");
    expect(body).toContain("return membership::answer(&name);");
    const asked = body.indexOf("membership::answers");
    // Before the state lookup and the downloads table as well as the call into the core's
    // table (`forward`): until the database has opened, a name asked after `try_state` is
    // answered "the app is still starting.", and the Sync panel would draw nothing where the
    // host's sentence belongs.
    for (const later of ["try_state", "downloads::answers", "forward(&state"]) {
      expect(body.indexOf(later), later).toBeGreaterThan(-1);
      expect(asked, later).toBeLessThan(body.indexOf(later));
    }
    // The command reaches the table through `forward` and never round it.
    expect(body).not.toContain("grimoire_core::dispatch");
    // One call into the core's table in the whole host, and it is the reworded one: a second
    // site that skipped `reword` would pass the pattern below as long as any one site had it.
    // `reword` is told the command's name, because its last fence applies to sync commands
    // only.
    expect(lightLib.match(/grimoire_core::dispatch\(/g)).toHaveLength(1);
    expect(forwardBody()).toMatch(
      /grimoire_core::dispatch\([\s\S]*?\)\s*\.await\s*\.map_err\(\|(\w+)\| membership::reword\(name, \1\)\)/,
    );
  });

  it("rewords the error log's rows as well, because the core writes the sentences there", () => {
    // The core records the key check's 401 sentence under `Source::Relay` as it happens — at
    // pairing, on the sync after it and on every launch of a group nobody turned sync on for —
    // and Settings → Errors reads those rows through `error_log_list`, whose `Ok` answer is not
    // an error and never meets `reword`.
    expect(literal("ERROR_LOG")).toBe("error_log_list");
    expect(coreCommands).toMatch(/\bread error_log_list in /);
    expect(forwardBody()).toContain("membership::reword_rows");
    expect(forwardBody()).toContain("name == membership::ERROR_LOG");
  });

  it("refuses both halves of connecting", () => {
    expect(lightMembership).toContain('const BEGIN: &str = "sync_patreon_begin";');
    expect(lightMembership).toContain('const CLAIM: &str = "sync_patreon_claim";');
    expect(lightMembership).toMatch(/name == ELSEWHERE \|\| name == BEGIN \|\| name == CLAIM/);
    // `answer` hands every name that is not ELSEWHERE the refusal, never an `Ok`.
    expect(lightMembership).toContain("Err(NOT_OFFERED.to_owned())");
  });

  it("knows every command of the core's table that is about a membership", () => {
    // Every name the table registers, whatever its kind of lane: `read`, `write`, `owned`,
    // `blocking`, `task` and `bytes` are the six keywords `commands.rs` registers with
    // (the `for … in` lines are loops, not registrations).
    const registered = [
      ...coreCommands.matchAll(/^\s*(?:read|write|owned|blocking|task|bytes) (\w+) in /gm),
    ].map((m) => m[1]);
    // A pattern that matched nothing would pass the next check as vacuously as it likes.
    expect(registered.length).toBeGreaterThan(100);
    // These three, and only these. A fourth is a command this host must decide about — refuse
    // it, as the first two are, or answer it — before it ships: a name renamed there would leave
    // this host refusing a name nobody sends, and the page's presses reaching the table.
    expect(registered.filter((name) => /patreon|supporter|membership|claim/.test(name)).sort()).toEqual([
      "sync_patreon_begin",
      "sync_patreon_claim",
      "sync_supporter_status",
    ]);
  });

  it("rewords the sentences the core still writes for a lapse and for a key it does not know", () => {
    // The host matches the core's words by value. Were the core's reworded, the host would
    // stop matching and a phone would read the membership sentence again.
    const tail = literal("LAPSED_TAIL");
    expect(tail).toBe("; the membership has ended");
    expect(coreSyncClient).toContain(`the relay answered 401 to {what}${tail}`);
    // The key check's 401 has no const in the core: the host matches its opening words, and
    // the sentence that follows them there still tells a reader to reconnect Patreon.
    const head = literal("KEY_CHECK_HEAD");
    expect(head).toBe("the relay did not recognise this device's group key.");
    expect(coreSyncClient).toContain(`"${head} If your devices synced \\`);
    expect(lightMembership).toContain("said.find(KEY_CHECK_HEAD)");
  });

  it("says nothing a reader could pay for, in any sentence of its own", () => {
    const declared = lightMembership.match(/^(?:pub )?const [A-Z_]+: &str\b/gm) ?? [];
    const matched = [...lightMembership.matchAll(/^(?:pub )?const [A-Z_]+: &str =\s*"([^"\\]+)";/gm)];
    // A constant whose literal holds a backslash or an escaped quote is not matched by the
    // pattern above and would be skipped without a word: every declaration must be read.
    expect(matched).toHaveLength(declared.length);
    const own = matched
      .map((m) => m[1])
      // Five literals are not sentences a reader is shown: the command this host answers, the
      // two it refuses, the command whose rows it rewords, and the core's lapse tail, which holds
      // the very word this test forbids because it is what the host looks for. KEY_CHECK_HEAD is
      // also the core's words but holds none of them, so it stays in the scanned set.
      .filter(
        (text) =>
          text !== MEMBERSHIP_ELSEWHERE &&
          !text.startsWith("sync_patreon_") &&
          text !== "error_log_list" &&
          text !== "; the membership has ended",
      );
    // Twelve declared, five filtered out, seven left: SENTENCE, NOT_OFFERED, LAPSED_HERE,
    // NO_SYNC_YET, KEY_CHECK_HEAD, KEY_CHECK_HERE and UNSAID.
    expect(declared).toHaveLength(12);
    expect(own).toHaveLength(7);
    for (const text of own) {
      expect(text, text).not.toMatch(/patreon|membership|supporter|supporting|payment|pledge|subscri|price/i);
    }
  });
});
