/**
 * The card corpus every story draws on: 42 real printings, straight out of the
 * local card database.
 *
 * **Generated by `scripts/gen-storybook-cards.mjs` — do not edit by hand.** Re-run it to
 * refresh against a newer sync. Every value here is a column of `cards` as the app's own
 * ingest wrote it, which is the point: a hand-written fixture agrees with the code that
 * reads it rather than with the data, and the two drift apart in exactly the places a story
 * exists to show. The `legalities` blobs are the case that settled it — all 116,694 rows in
 * the database carry exactly 23 keys, and the set grows with every new format.
 *
 * Each row's comment names the render branch it exists to make reachable. Deleting a row
 * deletes that branch's only fixture.
 *
 * Nothing is imported here on purpose: `tsconfig` has `noUnusedLocals`, and a type pulled in
 * only to be named in a doc comment is an unused import that fails `npm run build`. The DTO
 * names below are prose; `src/lib/ipc.ts` is where they are defined.
 */

/**
 * One row of the fake `cards` table.
 *
 * A **row**, not a DTO. It carries the union of the columns the three card-shaped DTOs are
 * derived from, so `db.ts` can build a `CardSummary`, a `CardDetail` and a `Printing` from
 * the same row without any of them being stored — which is what makes a fixture unable to
 * answer the same question two ways.
 *
 * Field names and nullability mirror `src-tauri/src/card.rs`'s `card_row`, because the DTOs
 * derived from it must come out identical to Rust's. Two rules from CLAUDE.md are
 * load-bearing here and are easy to get wrong from memory:
 *
 * * `colors` and `colorIdentity` are **concatenated letters** (`"WU"`), not JSON arrays.
 *   `JSON.parse` throws on them. Colourless is `""`, not `null`.
 * * `legalities`, `prices`, `finishes` and `faces` **are** JSON, as strings.
 */
export interface FakeCard {
  id: string;
  oracleId: string;
  name: string;
  setCode: string;
  setName: string;
  collectorNumber: string;
  lang: string;
  rarity: string | null;
  layout: string;
  manaCost: string | null;
  cmc: number | null;
  typeLine: string | null;
  oracleText: string | null;
  colors: string | null;
  colorIdentity: string | null;
  power: string | null;
  toughness: string | null;
  /** JSON object of 23 keys — measured, not assumed, and it grows with the formats. */
  legalities: string;
  /** JSON object: `usd`, `usd_foil`, `usd_etched`, `eur`, `eur_foil`, `tix`. Decimal
   *  **strings**, because that is what Scryfall publishes and what `prices.ts` parses. */
  prices: string;
  /** JSON array: `["nonfoil","foil"]`. */
  finishes: string;
  /**
   * JSON: Scryfall's `card_faces` array, `"[]"` for a single-faced printing.
   *
   * The array a `CardFace` is *derived* from, not an array of them — `card.rs`'s
   * `parse_faces` picks five keys out of each face and the deck validator reads the per-face
   * cost, mana value and P/T, so the row has to carry what both of them read. The one thing
   * dropped from the real blob is each face's `image_uris`; see the generator for why.
   */
  faces: string;
  artist: string | null;
  illustrationId: string | null;
  releasedAt: string;
  imageStatus: string | null;
  promo: boolean;
  fullArt: boolean;
  frameEffects: string | null;
  borderColor: string | null;
  gameChanger: boolean;
  /** Printed at uncommon on **some** printing of this oracle card — Pauper Commander
   *  eligibility, which is a fact about the card and never about the printing shown. */
  everUncommon: boolean;
  /** Digital-only. The search's `paperOnly` default hides these. */
  digital: boolean;
  /** Real Scryfall `art_crop` URL, used only under the "Live" art toolbar global — no image
   *  bytes are committed to this repository. `null` for a printing with no art anywhere. */
  artCropUrl: string | null;
  /** Real Scryfall `normal` URL, same. */
  normalUrl: string | null;
}

export const CARDS: FakeCard[] = [
  // The printings list's oldest row: common, black border, nonfoil only, and the four-figure end of
  // a common card's price range.
  {
    id: "d573ef03-4730-45aa-93dd-e45ac1dbaf4a",
    oracleId: "4457ed35-7c10-48c8-9776-456485fdf070",
    name: "Lightning Bolt",
    setCode: "lea",
    setName: "Limited Edition Alpha",
    collectorNumber: "161",
    lang: "en",
    rarity: "common",
    layout: "normal",
    manaCost: "{R}",
    cmc: 1,
    typeLine: "Instant",
    oracleText: "Lightning Bolt deals 3 damage to any target.",
    colors: "R",
    colorIdentity: "R",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"banned","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"legal","pauper":"legal","paupercommander":"legal","penny":"not_legal","pioneer":"not_legal","predh":"legal","premodern":"legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"409.41","eur_foil":null,"tix":null,"usd":"620.00","usd_etched":null,"usd_foil":null}',
    finishes: '["nonfoil"]',
    faces: "[]",
    artist: "Christopher Rush",
    illustrationId: "2cb6200c-d05b-419c-bd10-8b9c146e2339",
    releasedAt: "1993-08-05",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: true,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/d/5/d573ef03-4730-45aa-93dd-e45ac1dbaf4a.jpg?1783948684",
    normalUrl:
      "https://cards.scryfall.io/normal/front/d/5/d573ef03-4730-45aa-93dd-e45ac1dbaf4a.jpg?1783948684",
  },

  // The same card at a different rarity — a printings list that showed one gem for the card rather
  // than one per row would look right here and be wrong.
  {
    id: "f29ba16f-c8fb-42fe-aabf-87089cb214a7",
    oracleId: "4457ed35-7c10-48c8-9776-456485fdf070",
    name: "Lightning Bolt",
    setCode: "2x2",
    setName: "Double Masters 2022",
    collectorNumber: "117",
    lang: "en",
    rarity: "uncommon",
    layout: "normal",
    manaCost: "{R}",
    cmc: 1,
    typeLine: "Instant",
    oracleText: "Lightning Bolt deals 3 damage to any target.",
    colors: "R",
    colorIdentity: "R",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"banned","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"legal","paupercommander":"legal","penny":"not_legal","pioneer":"not_legal","predh":"legal","premodern":"legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"1.57","eur_foil":"2.22","tix":"0.99","usd":"2.50","usd_etched":null,"usd_foil":"2.39"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Christopher Moeller",
    illustrationId: "013e7eda-ef8e-44cd-9832-4033d9de1c34",
    releasedAt: "2022-07-08",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: true,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/f/2/f29ba16f-c8fb-42fe-aabf-87089cb214a7.jpg?1783921885",
    normalUrl:
      "https://cards.scryfall.io/normal/front/f/2/f29ba16f-c8fb-42fe-aabf-87089cb214a7.jpg?1783921885",
  },

  // Borderless, full-art, `frameEffects` set: the three fields a printings row is *distinguished*
  // by, all at once.
  {
    id: "4f43c378-9e6a-4ece-9c24-5dc08c977746",
    oracleId: "4457ed35-7c10-48c8-9776-456485fdf070",
    name: "Lightning Bolt",
    setCode: "sld",
    setName: "Secret Lair Drop",
    collectorNumber: "1638",
    lang: "en",
    rarity: "rare",
    layout: "normal",
    manaCost: "{R}",
    cmc: 1,
    typeLine: "Instant",
    oracleText: "Lightning Bolt deals 3 damage to any target.",
    colors: "R",
    colorIdentity: "R",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"banned","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"legal","paupercommander":"legal","penny":"not_legal","pioneer":"not_legal","predh":"legal","premodern":"legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"3.92","eur_foil":null,"tix":null,"usd":"3.03","usd_etched":null,"usd_foil":null}',
    finishes: '["nonfoil"]',
    faces: "[]",
    artist: "Desmuncubic",
    illustrationId: "c43c490f-ef7e-4d06-ae86-fa186f6cc902",
    releasedAt: "2024-04-08",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: true,
    frameEffects: '["inverted"]',
    borderColor: "borderless",
    gameChanger: false,
    everUncommon: true,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/4/f/4f43c378-9e6a-4ece-9c24-5dc08c977746.jpg?1783912016",
    normalUrl:
      "https://cards.scryfall.io/normal/front/4/f/4f43c378-9e6a-4ece-9c24-5dc08c977746.jpg?1783912016",
  },

  // `lang` is not always `en`. Every language is listed in a printings list, and a row that assumes
  // English silently mislabels this one.
  {
    id: "b14fae63-2e82-49c1-8e62-d84a65f27479",
    oracleId: "4457ed35-7c10-48c8-9776-456485fdf070",
    name: "Lightning Bolt",
    setCode: "sta",
    setName: "Strixhaven Mystical Archive",
    collectorNumber: "105",
    lang: "ja",
    rarity: "rare",
    layout: "normal",
    manaCost: "{R}",
    cmc: 1,
    typeLine: "Instant",
    oracleText: "Lightning Bolt deals 3 damage to any target.",
    colors: "R",
    colorIdentity: "R",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"banned","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"legal","paupercommander":"legal","penny":"not_legal","pioneer":"not_legal","predh":"legal","premodern":"legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"15.45","eur_foil":"28.48","tix":"19.88","usd":"17.85","usd_etched":"18.68","usd_foil":"23.85"}',
    finishes: '["nonfoil","foil","etched"]',
    faces: "[]",
    artist: "Ezoi",
    illustrationId: "b1698749-41b9-41fc-80f4-f54a7038b454",
    releasedAt: "2021-04-23",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: true,
    frameEffects: null,
    borderColor: "borderless",
    gameChanger: false,
    everUncommon: true,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/b/1/b14fae63-2e82-49c1-8e62-d84a65f27479.jpg?1783927405",
    normalUrl:
      "https://cards.scryfall.io/normal/front/b/1/b14fae63-2e82-49c1-8e62-d84a65f27479.jpg?1783927405",
  },

  // Four figures, and `banned` in nearly every format — the price formatter's widest number and the
  // legality panel's longest red column.
  {
    id: "b0faa7f2-b547-42c4-a810-839da50dadfe",
    oracleId: "5089ec1a-f881-4d55-af14-5d996171203b",
    name: "Black Lotus",
    setCode: "lea",
    setName: "Limited Edition Alpha",
    collectorNumber: "232",
    lang: "en",
    rarity: "rare",
    layout: "normal",
    manaCost: "{0}",
    cmc: 0,
    typeLine: "Artifact",
    oracleText: "{T}, Sacrifice this artifact: Add three mana of any one color.",
    colors: "",
    colorIdentity: "",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"not_legal","commander":"banned","competitivebrawl":"not_legal","duel":"banned","future":"not_legal","gladiator":"not_legal","historic":"not_legal","legacy":"banned","modern":"not_legal","oathbreaker":"banned","oldschool":"restricted","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"banned","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"not_legal","tlr":"legal","vintage":"restricted"}',
    prices:
      '{"eur":"38719.86","eur_foil":null,"tix":"491.06","usd":null,"usd_etched":null,"usd_foil":null}',
    finishes: '["nonfoil"]',
    faces: "[]",
    artist: "Christopher Rush",
    illustrationId: "54436824-977b-4dc7-8de1-8498e73e5ef2",
    releasedAt: "1993-08-05",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/b/0/b0faa7f2-b547-42c4-a810-839da50dadfe.jpg?1783948669",
    normalUrl:
      "https://cards.scryfall.io/normal/front/b/0/b0faa7f2-b547-42c4-a810-839da50dadfe.jpg?1783948669",
  },

  // `digital: true` **and** rarity `bonus`, which has no colour token: the paper-only filter has
  // something to hide, and `RarityGem` has its uncoloured branch.
  {
    id: "bd8fa327-dd41-4737-8f19-2cf5eb1f7cdd",
    oracleId: "5089ec1a-f881-4d55-af14-5d996171203b",
    name: "Black Lotus",
    setCode: "vma",
    setName: "Vintage Masters",
    collectorNumber: "4",
    lang: "en",
    rarity: "bonus",
    layout: "normal",
    manaCost: "{0}",
    cmc: 0,
    typeLine: "Artifact",
    oracleText: "{T}, Sacrifice this artifact: Add three mana of any one color.",
    colors: "",
    colorIdentity: "",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"not_legal","commander":"banned","competitivebrawl":"not_legal","duel":"banned","future":"not_legal","gladiator":"not_legal","historic":"not_legal","legacy":"banned","modern":"not_legal","oathbreaker":"banned","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"banned","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"not_legal","tlr":"legal","vintage":"restricted"}',
    prices:
      '{"eur":null,"eur_foil":null,"tix":"46.51","usd":null,"usd_etched":null,"usd_foil":null}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Chris Rahn",
    illustrationId: "da62ded1-bedd-44c6-8950-ca56e691a899",
    releasedAt: "2014-06-16",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: true,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/b/d/bd8fa327-dd41-4737-8f19-2cf5eb1f7cdd.jpg?1783939332",
    normalUrl:
      "https://cards.scryfall.io/normal/front/b/d/bd8fa327-dd41-4737-8f19-2cf5eb1f7cdd.jpg?1783939332",
  },

  // `restricted` in vintage — the `max_one` restricted semantic, which is a different rule from
  // `banned` and must not render as one.
  {
    id: "70e7ddf2-5604-41e7-bb9d-ddd03d3e9d0b",
    oracleId: "550c74d4-1fcb-406a-b02a-639a760a4380",
    name: "Ancestral Recall",
    setCode: "lea",
    setName: "Limited Edition Alpha",
    collectorNumber: "47",
    lang: "en",
    rarity: "rare",
    layout: "normal",
    manaCost: "{U}",
    cmc: 1,
    typeLine: "Instant",
    oracleText: "Target player draws three cards.",
    colors: "U",
    colorIdentity: "U",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"not_legal","commander":"banned","competitivebrawl":"not_legal","duel":"banned","future":"not_legal","gladiator":"not_legal","historic":"not_legal","legacy":"banned","modern":"not_legal","oathbreaker":"banned","oldschool":"restricted","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"banned","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"not_legal","tlr":"legal","vintage":"restricted"}',
    prices:
      '{"eur":"17278.17","eur_foil":null,"tix":"123.48","usd":null,"usd_etched":null,"usd_foil":null}',
    finishes: '["nonfoil"]',
    faces: "[]",
    artist: "Mark Poole",
    illustrationId: "d20eda7b-a902-4c00-bdab-601059e417b5",
    releasedAt: "1993-08-05",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/7/0/70e7ddf2-5604-41e7-bb9d-ddd03d3e9d0b.jpg?1783948708",
    normalUrl:
      "https://cards.scryfall.io/normal/front/7/0/70e7ddf2-5604-41e7-bb9d-ddd03d3e9d0b.jpg?1783948708",
  },

  // A full-art basic: unlimited copies in a singleton deck, and `fullArt: true`.
  {
    id: "5dda1113-352c-471a-a7e0-a9a3cb3f19c5",
    oracleId: "b34bb2dc-c1af-4d77-b0b3-a0fb342a5fc6",
    name: "Forest",
    setCode: "unf",
    setName: "Unfinity",
    collectorNumber: "239",
    lang: "en",
    rarity: "common",
    layout: "normal",
    manaCost: "",
    cmc: 0,
    typeLine: "Basic Land — Forest",
    oracleText: "({T}: Add {G}.)",
    colors: "",
    colorIdentity: "G",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"legal","paupercommander":"legal","penny":"legal","pioneer":"legal","predh":"legal","premodern":"legal","standard":"legal","standardbrawl":"legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"0.75","eur_foil":"1.38","tix":"0.88","usd":"0.98","usd_etched":null,"usd_foil":"1.18"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Adam Paquette",
    illustrationId: "77d2dcc5-054b-42d9-8e43-d96fe0d773ad",
    releasedAt: "2022-10-07",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: true,
    frameEffects: '["inverted"]',
    borderColor: "borderless",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/5/d/5dda1113-352c-471a-a7e0-a9a3cb3f19c5.jpg?1783920466",
    normalUrl:
      "https://cards.scryfall.io/normal/front/5/d/5dda1113-352c-471a-a7e0-a9a3cb3f19c5.jpg?1783920466",
  },

  // A plain basic, so the full-art branch has a non-full-art twin to be told apart from.
  {
    id: "90a57c0e-fa61-45ef-955d-d296403967d5",
    oracleId: "b2c6aa39-2d2a-459c-a555-fb48ba993373",
    name: "Island",
    setCode: "lea",
    setName: "Limited Edition Alpha",
    collectorNumber: "288",
    lang: "en",
    rarity: "common",
    layout: "normal",
    manaCost: "",
    cmc: 0,
    typeLine: "Basic Land — Island",
    oracleText: "({T}: Add {U}.)",
    colors: "",
    colorIdentity: "U",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"legal","pauper":"legal","paupercommander":"legal","penny":"legal","pioneer":"legal","predh":"legal","premodern":"legal","standard":"legal","standardbrawl":"legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"48.75","eur_foil":null,"tix":null,"usd":"73.96","usd_etched":null,"usd_foil":null}',
    finishes: '["nonfoil"]',
    faces: "[]",
    artist: "Mark Poole",
    illustrationId: "2c1e9dcd-a55e-40b7-80e4-6741e3f16ae0",
    releasedAt: "1993-08-05",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/9/0/90a57c0e-fa61-45ef-955d-d296403967d5.jpg?1783948658",
    normalUrl:
      "https://cards.scryfall.io/normal/front/9/0/90a57c0e-fa61-45ef-955d-d296403967d5.jpg?1783948658",
  },

  // `layout: "saga"` on a land, with an empty mana cost — a cost line that must render as nothing
  // rather than as `{}`.
  {
    id: "c1e0f201-42cb-46a1-901a-65bb4fc18f6c",
    oracleId: "4c6a0c30-b547-4eff-8ff4-0ca25803c076",
    name: "Urza's Saga",
    setCode: "mh2",
    setName: "Modern Horizons 2",
    collectorNumber: "259",
    lang: "en",
    rarity: "rare",
    layout: "saga",
    manaCost: "",
    cmc: 0,
    typeLine: "Enchantment Land — Urza's Saga",
    oracleText:
      '(As this Saga enters and after your draw step, add a lore counter. Sacrifice after III.)\nI — This Saga gains "{T}: Add {C}."\nII — This Saga gains "{2}, {T}: Create a 0/0 colorless Construct artifact creature token with \'This token gets +1/+1 for each artifact you control.\'"\nIII — Search your library for an artifact card with mana cost {0} or {1}, put it onto the battlefield, then shuffle.',
    colors: "",
    colorIdentity: "",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"not_legal","commander":"legal","competitivebrawl":"not_legal","duel":"legal","future":"not_legal","gladiator":"not_legal","historic":"not_legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"not_legal","tlr":"legal","vintage":"restricted"}',
    prices:
      '{"eur":"38.87","eur_foil":"68.21","tix":"12.58","usd":"39.86","usd_etched":null,"usd_foil":"67.89"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Titus Lunter",
    illustrationId: "ef72bbb2-d10c-45a2-a3b8-3ba591379aa5",
    releasedAt: "2021-06-18",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/c/1/c1e0f201-42cb-46a1-901a-65bb4fc18f6c.jpg?1783926791",
    normalUrl:
      "https://cards.scryfall.io/normal/front/c/1/c1e0f201-42cb-46a1-901a-65bb4fc18f6c.jpg?1783926791",
  },

  // `gameChanger: true` on a land — the Commander bracket chip on a card with no mana cost at all.
  {
    id: "30e401e3-282b-4524-87e1-c6cd50cd6d00",
    oracleId: "23467047-6dba-4498-b783-1ebc4f74b8c2",
    name: "Ancient Tomb",
    setCode: "tmp",
    setName: "Tempest",
    collectorNumber: "315",
    lang: "en",
    rarity: "uncommon",
    layout: "normal",
    manaCost: "",
    cmc: 0,
    typeLine: "Land",
    oracleText: "{T}: Add {C}{C}. This land deals 2 damage to you.",
    colors: "",
    colorIdentity: "",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"banned","commander":"legal","competitivebrawl":"legal","duel":"banned","future":"not_legal","gladiator":"legal","historic":"banned","legacy":"legal","modern":"not_legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"legal","premodern":"legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"94.46","eur_foil":null,"tix":"34.74","usd":"123.23","usd_etched":null,"usd_foil":null}',
    finishes: '["nonfoil"]',
    faces: "[]",
    artist: "Colin MacNeil",
    illustrationId: "25b63436-d094-4014-9bda-d97e902da980",
    releasedAt: "1997-10-14",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: true,
    everUncommon: true,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/3/0/30e401e3-282b-4524-87e1-c6cd50cd6d00.jpg?1783946598",
    normalUrl:
      "https://cards.scryfall.io/normal/front/3/0/30e401e3-282b-4524-87e1-c6cd50cd6d00.jpg?1783946598",
  },

  // `transform`: two faces, the back with an empty mana cost that must not render as a cost pill,
  // and a flip control addressed by face index.
  {
    id: "11bf83bb-c95b-4b4f-9a56-ce7a1816307a",
    oracleId: "edd531b9-f615-4399-8c8c-1c5e18c4acbf",
    name: "Delver of Secrets // Insectile Aberration",
    setCode: "isd",
    setName: "Innistrad",
    collectorNumber: "51",
    lang: "en",
    rarity: "common",
    layout: "transform",
    manaCost: "{U}",
    cmc: 1,
    typeLine: "Creature — Human Wizard // Creature — Human Insect",
    oracleText: null,
    colors: "U",
    colorIdentity: "U",
    power: "1",
    toughness: "1",
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"legal","paupercommander":"legal","penny":"not_legal","pioneer":"legal","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"0.54","eur_foil":"2.81","tix":"0.03","usd":"0.37","usd_etched":null,"usd_foil":"2.08"}',
    finishes: '["nonfoil","foil"]',
    faces:
      '[{"name":"Delver of Secrets","mana_cost":"{U}","type_line":"Creature — Human Wizard","oracle_text":"At the beginning of your upkeep, look at the top card of your library. You may reveal that card. If an instant or sorcery card is revealed this way, transform this creature.","colors":["U"],"power":"1","toughness":"1","artist":"Nils Hamm","illustration_id":"1c2fee9b-89ea-4ab1-a751-451c3cd65a88"},{"name":"Insectile Aberration","mana_cost":"","type_line":"Creature — Human Insect","oracle_text":"Flying","colors":["U"],"color_indicator":["U"],"power":"3","toughness":"2","artist":"Nils Hamm","illustration_id":"c2b5f731-771b-4949-90f3-0ad40d676100"}]',
    artist: "Nils Hamm",
    illustrationId: null,
    releasedAt: "2011-09-30",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: '["sunmoondfc"]',
    borderColor: "black",
    gameChanger: false,
    everUncommon: true,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/1/1/11bf83bb-c95b-4b4f-9a56-ce7a1816307a.jpg?1783940984",
    normalUrl:
      "https://cards.scryfall.io/normal/front/1/1/11bf83bb-c95b-4b4f-9a56-ce7a1816307a.jpg?1783940984",
  },

  // `split`: two faces, two costs, one card, and a `//` name the search has to match either half
  // of.
  {
    id: "f98f4538-5b5b-475d-b98f-49d01dae6f04",
    oracleId: "ae92942b-919c-4ea9-b693-85fcef765d5a",
    name: "Fire // Ice",
    setCode: "apc",
    setName: "Apocalypse",
    collectorNumber: "128",
    lang: "en",
    rarity: "uncommon",
    layout: "split",
    manaCost: "{1}{R} // {1}{U}",
    cmc: 4,
    typeLine: "Instant // Instant",
    oracleText: null,
    colors: "RU",
    colorIdentity: "RU",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"not_legal","commander":"legal","competitivebrawl":"not_legal","duel":"legal","future":"not_legal","gladiator":"not_legal","historic":"not_legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"legal","paupercommander":"legal","penny":"not_legal","pioneer":"not_legal","predh":"legal","premodern":"legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"not_legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"2.14","eur_foil":"54.14","tix":"0.82","usd":"2.56","usd_etched":null,"usd_foil":"59.72"}',
    finishes: '["nonfoil","foil"]',
    faces:
      '[{"name":"Fire","mana_cost":"{1}{R}","type_line":"Instant","oracle_text":"Fire deals 2 damage divided as you choose among one or two targets.","artist":"David Martin","illustration_id":"c890cb20-7e04-4ad0-96a6-8854cd409c14"},{"name":"Ice","mana_cost":"{1}{U}","type_line":"Instant","oracle_text":"Tap target permanent.\\nDraw a card.","artist":"Franz Vohwinkel"}]',
    artist: "David Martin & Franz Vohwinkel",
    illustrationId: "c890cb20-7e04-4ad0-96a6-8854cd409c14",
    releasedAt: "2001-06-04",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: true,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/f/9/f98f4538-5b5b-475d-b98f-49d01dae6f04.jpg?1783945328",
    normalUrl:
      "https://cards.scryfall.io/normal/front/f/9/f98f4538-5b5b-475d-b98f-49d01dae6f04.jpg?1783945328",
  },

  // `adventure`: two faces where only the front is a permanent — the mana value is the creature's,
  // not the sum.
  {
    id: "09fd2d9c-1793-4beb-a3fb-7a869f660cd4",
    oracleId: "d6d72f5f-8f5d-4180-b514-f22ff5482902",
    name: "Bonecrusher Giant // Stomp",
    setCode: "eld",
    setName: "Throne of Eldraine",
    collectorNumber: "115",
    lang: "en",
    rarity: "rare",
    layout: "adventure",
    manaCost: "{2}{R} // {1}{R}",
    cmc: 3,
    typeLine: "Creature — Giant // Instant — Adventure",
    oracleText: null,
    colors: "R",
    colorIdentity: "R",
    power: "4",
    toughness: "3",
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"legal","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"0.30","eur_foil":"1.13","tix":"0.02","usd":"0.33","usd_etched":null,"usd_foil":"0.66"}',
    finishes: '["nonfoil","foil"]',
    faces:
      '[{"name":"Bonecrusher Giant","mana_cost":"{2}{R}","type_line":"Creature — Giant","oracle_text":"Whenever this creature becomes the target of a spell, this creature deals 2 damage to that spell\'s controller.","power":"4","toughness":"3","artist":"Victor Adame Minguez","illustration_id":"c7f49422-def6-4502-bc02-38aee9924371"},{"name":"Stomp","mana_cost":"{1}{R}","type_line":"Instant — Adventure","oracle_text":"Damage can\'t be prevented this turn. Stomp deals 2 damage to any target.","artist":"Victor Adame Minguez"}]',
    artist: "Victor Adame Minguez",
    illustrationId: "c7f49422-def6-4502-bc02-38aee9924371",
    releasedAt: "2019-10-04",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/0/9/09fd2d9c-1793-4beb-a3fb-7a869f660cd4.jpg?1783932628",
    normalUrl:
      "https://cards.scryfall.io/normal/front/0/9/09fd2d9c-1793-4beb-a3fb-7a869f660cd4.jpg?1783932628",
  },

  // `modal_dfc` with an `{X}` in the cost: the back is a land, so the colour identity folds in a
  // face the front never shows.
  {
    id: "67f4c93b-080c-4196-b095-6a120a221988",
    oracleId: "562d71b9-1646-474e-9293-55da6947a758",
    name: "Agadeem's Awakening // Agadeem, the Undercrypt",
    setCode: "znr",
    setName: "Zendikar Rising",
    collectorNumber: "90",
    lang: "en",
    rarity: "mythic",
    layout: "modal_dfc",
    manaCost: "{X}{B}{B}{B}",
    cmc: 3,
    typeLine: "Sorcery // Land",
    oracleText: null,
    colors: "B",
    colorIdentity: "B",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"legal","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"23.13","eur_foil":"26.35","tix":"2.03","usd":"28.38","usd_etched":null,"usd_foil":"31.58"}',
    finishes: '["nonfoil","foil"]',
    faces:
      '[{"name":"Agadeem\'s Awakening","mana_cost":"{X}{B}{B}{B}","type_line":"Sorcery","oracle_text":"Return from your graveyard to the battlefield any number of target creature cards that each have a different mana value X or less.","colors":["B"],"artist":"Dmitry Burmak","illustration_id":"9c4fd66b-b125-4e63-a0ee-d49ec58fc381"},{"name":"Agadeem, the Undercrypt","mana_cost":"","type_line":"Land","oracle_text":"As this land enters, you may pay 3 life. If you don\'t, it enters tapped.\\n{T}: Add {B}.","colors":[],"artist":"Dmitry Burmak","illustration_id":"259cbafd-c75a-45b1-9b1e-a428796aa977"}]',
    artist: "Dmitry Burmak",
    illustrationId: null,
    releasedAt: "2020-09-25",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/6/7/67f4c93b-080c-4196-b095-6a120a221988.jpg?1783929388",
    normalUrl:
      "https://cards.scryfall.io/normal/front/6/7/67f4c93b-080c-4196-b095-6a120a221988.jpg?1783929388",
  },

  // `meld`: the layout whose other half is a third card, and the one a face-count assumption breaks
  // on.
  {
    id: "27907985-b5f6-4098-ab43-15a0c2bf94d5",
    oracleId: "bce7e45d-b2c5-43aa-91a6-3a3c24f30850",
    name: "Bruna, the Fading Light",
    setCode: "emn",
    setName: "Eldritch Moon",
    collectorNumber: "15",
    lang: "en",
    rarity: "rare",
    layout: "meld",
    manaCost: "{5}{W}{W}",
    cmc: 7,
    typeLine: "Legendary Creature — Angel Horror",
    oracleText:
      "When you cast this spell, you may return target Angel or Human creature card from your graveyard to the battlefield.\nFlying, vigilance\n(Melds with Gisela, the Broken Blade.)",
    colors: "W",
    colorIdentity: "W",
    power: "5",
    toughness: "7",
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"legal","pioneer":"legal","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"not_legal","vintage":"legal"}',
    prices:
      '{"eur":"1.67","eur_foil":"5.72","tix":"0.02","usd":"3.77","usd_etched":null,"usd_foil":"9.23"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Clint Cearley",
    illustrationId: "4c8cee4a-a9a4-42eb-9cbf-fcc6c6344d00",
    releasedAt: "2016-07-22",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: '["mooneldrazidfc"]',
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/2/7/27907985-b5f6-4098-ab43-15a0c2bf94d5.jpg?1783937523",
    normalUrl:
      "https://cards.scryfall.io/normal/front/2/7/27907985-b5f6-4098-ab43-15a0c2bf94d5.jpg?1783937523",
  },

  // `imageStatus: "missing"` with no image URLs at all — the no-image branch. All 162 rows in that
  // state are `art_series` (measured 2026-08-09), so this is what that branch really looks like.
  {
    id: "0310667f-7f88-42ec-978c-749c94769cf8",
    oracleId: "ba15f299-ec6d-4515-8648-b0843d7a438a",
    name: "Prismatic Ending // Prismatic Ending",
    setCode: "amh2",
    setName: "Modern Horizons 2 Art Series",
    collectorNumber: "5s",
    lang: "en",
    rarity: "common",
    layout: "art_series",
    manaCost: "",
    cmc: 0,
    typeLine: "Card // Card",
    oracleText: null,
    colors: "",
    colorIdentity: "",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"not_legal","commander":"not_legal","competitivebrawl":"not_legal","duel":"not_legal","future":"not_legal","gladiator":"not_legal","historic":"not_legal","legacy":"not_legal","modern":"not_legal","oathbreaker":"not_legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"not_legal","tlr":"not_legal","vintage":"not_legal"}',
    prices: '{"eur":null,"eur_foil":null,"tix":null,"usd":null,"usd_etched":null,"usd_foil":null}',
    finishes: '["nonfoil"]',
    faces:
      '[{"name":"Prismatic Ending","mana_cost":"","type_line":"Card","oracle_text":"","colors":[],"artist":"John Stanko","illustration_id":"78feeb10-4d5b-49f3-9fda-17da6bee148b"},{"name":"Prismatic Ending","mana_cost":"","type_line":"Card","oracle_text":"","colors":[],"artist":"John Stanko"}]',
    artist: "John Stanko",
    illustrationId: null,
    releasedAt: "2021-06-18",
    imageStatus: "missing",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "borderless",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl: null,
    normalUrl: null,
  },

  // A Vehicle **with a P/T box** — CR 903.3 makes a commander of it, and that is unanswerable
  // without `power`/`toughness`.
  {
    id: "7832abb5-5107-4603-904e-491b221bd3e3",
    oracleId: "49136bdc-bc50-49a2-999a-1ef9c16ea130",
    name: "Smuggler's Copter",
    setCode: "kld",
    setName: "Kaladesh",
    collectorNumber: "235",
    lang: "en",
    rarity: "rare",
    layout: "normal",
    manaCost: "{2}",
    cmc: 2,
    typeLine: "Artifact — Vehicle",
    oracleText:
      "Flying\nWhenever this Vehicle attacks or blocks, you may draw a card. If you do, discard a card.\nCrew 1 (Tap any number of creatures you control with total power 1 or more: This Vehicle becomes an artifact creature until end of turn.)",
    colors: "",
    colorIdentity: "",
    power: "3",
    toughness: "3",
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"legal","pioneer":"legal","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"0.78","eur_foil":"5.34","tix":"0.02","usd":"0.86","usd_etched":null,"usd_foil":"5.65"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Florian de Gesincourt",
    illustrationId: "d7a7b98f-125c-41bc-bded-eae1ed4e57b4",
    releasedAt: "2016-09-30",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/7/8/7832abb5-5107-4603-904e-491b221bd3e3.jpg?1783937147",
    normalUrl:
      "https://cards.scryfall.io/normal/front/7/8/7832abb5-5107-4603-904e-491b221bd3e3.jpg?1783937147",
  },

  // Five-colour identity from a mono-white card: `colors` and `colorIdentity` disagree, which is
  // exactly why both are stored.
  {
    id: "56c1227e-bea7-47cb-bbec-389a3d585af5",
    oracleId: "d209b948-9afb-4fd1-a961-72c87282878c",
    name: "Kenrith, the Returned King",
    setCode: "eld",
    setName: "Throne of Eldraine",
    collectorNumber: "303",
    lang: "en",
    rarity: "mythic",
    layout: "normal",
    manaCost: "{4}{W}",
    cmc: 5,
    typeLine: "Legendary Creature — Human Noble",
    oracleText:
      "{R}: All creatures gain trample and haste until end of turn.\n{1}{G}: Put a +1/+1 counter on target creature.\n{2}{W}: Target player gains 5 life.\n{3}{U}: Target player draws a card.\n{4}{B}: Put target creature card from a graveyard onto the battlefield under its owner's control.",
    colors: "W",
    colorIdentity: "BGRUW",
    power: "5",
    toughness: "5",
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"legal","pioneer":"legal","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"not_legal","vintage":"legal"}',
    prices:
      '{"eur":"1.34","eur_foil":"4.67","tix":"0.02","usd":"1.28","usd_etched":null,"usd_foil":"2.26"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Kieran Yanner",
    illustrationId: "9db4d447-9074-430f-a7af-d416bc369c63",
    releasedAt: "2019-10-04",
    imageStatus: "highres_scan",
    promo: true,
    fullArt: false,
    frameEffects: '["legendary"]',
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/5/6/56c1227e-bea7-47cb-bbec-389a3d585af5.jpg?1783932556",
    normalUrl:
      "https://cards.scryfall.io/normal/front/5/6/56c1227e-bea7-47cb-bbec-389a3d585af5.jpg?1783932556",
  },

  // Partner, half one — two commanders in the zone is legal only for this pair-shaped rule.
  {
    id: "87eff269-c8d7-479e-ade4-383b8622e70d",
    oracleId: "d15642e4-e61c-4d29-af48-de837991245e",
    name: "Tymna the Weaver",
    setCode: "fca",
    setName: "Final Fantasy: Through the Ages",
    collectorNumber: "18",
    lang: "en",
    rarity: "rare",
    layout: "normal",
    manaCost: "{1}{W}{B}",
    cmc: 3,
    typeLine: "Legendary Creature — Human Cleric",
    oracleText:
      "Lifelink\nAt the beginning of each of your postcombat main phases, you may pay X life, where X is the number of opponents that were dealt combat damage this turn. If you do, draw X cards.\nPartner (You can have two commanders if both have partner.)",
    colors: "BW",
    colorIdentity: "BW",
    power: "2",
    toughness: "2",
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"not_legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"9.81","eur_foil":"46.78","tix":"0.67","usd":"11.08","usd_etched":null,"usd_foil":"68.41"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Yoshitaka Amano",
    illustrationId: "9fecddfe-8932-4cad-a2aa-080e6cdae288",
    releasedAt: "2025-06-13",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: true,
    frameEffects: '["legendary","inverted"]',
    borderColor: "borderless",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/8/7/87eff269-c8d7-479e-ade4-383b8622e70d.jpg?1783906389",
    normalUrl:
      "https://cards.scryfall.io/normal/front/8/7/87eff269-c8d7-479e-ade4-383b8622e70d.jpg?1783906389",
  },

  // Partner, half two. Their identities union to four colours, which no single commander here has.
  {
    id: "5f13417d-3fe1-4357-b826-cb48dd111247",
    oracleId: "3d867016-2601-4a37-a73d-308898d3bd37",
    name: "Thrasios, Triton Hero",
    setCode: "fca",
    setName: "Final Fantasy: Through the Ages",
    collectorNumber: "58",
    lang: "en",
    rarity: "mythic",
    layout: "normal",
    manaCost: "{G}{U}",
    cmc: 2,
    typeLine: "Legendary Creature — Merfolk Wizard",
    oracleText:
      "{4}: Scry 1, then reveal the top card of your library. If it's a land card, put it onto the battlefield tapped. Otherwise, draw a card.\nPartner (You can have two commanders if both have partner.)",
    colors: "GU",
    colorIdentity: "GU",
    power: "1",
    toughness: "3",
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"not_legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"15.40","eur_foil":"87.08","tix":"2.04","usd":"18.33","usd_etched":null,"usd_foil":"148.74"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Square Enix",
    illustrationId: "87f54fff-2b17-4190-b2f5-6a0647f83dfc",
    releasedAt: "2025-06-13",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: true,
    frameEffects: '["legendary","inverted"]',
    borderColor: "borderless",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/5/f/5f13417d-3fe1-4357-b826-cb48dd111247.jpg?1783906376",
    normalUrl:
      "https://cards.scryfall.io/normal/front/5/f/5f13417d-3fe1-4357-b826-cb48dd111247.jpg?1783906376",
  },

  // A companion, with its deck-building condition in the oracle text — the string `companions.ts`
  // re-derives the rule from.
  {
    id: "5ad36fb2-c44e-4085-ba0d-54277841ad3a",
    oracleId: "3bc757c1-3adb-4321-8832-8e1cc9e687f7",
    name: "Lurrus of the Dream-Den",
    setCode: "iko",
    setName: "Ikoria: Lair of Behemoths",
    collectorNumber: "226",
    lang: "en",
    rarity: "rare",
    layout: "normal",
    manaCost: "{1}{W/B}{W/B}",
    cmc: 3,
    typeLine: "Legendary Creature — Cat Nightmare",
    oracleText:
      "Companion — Each permanent card in your starting deck has mana value 2 or less. (If this card is your chosen companion, you may put it into your hand from outside the game for {3} as a sorcery.)\nLifelink\nOnce during each of your turns, you may cast a permanent spell with mana value 2 or less from your graveyard.",
    colors: "BW",
    colorIdentity: "BW",
    power: "3",
    toughness: "2",
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"banned","modern":"banned","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"legal","pioneer":"banned","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"1.45","eur_foil":"2.52","tix":"0.02","usd":"2.66","usd_etched":null,"usd_foil":"3.29"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Slawomir Maniak",
    illustrationId: "f715763e-13f5-4f16-87b6-466bf5dbffba",
    releasedAt: "2020-04-24",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: '["companion","legendary"]',
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/5/a/5ad36fb2-c44e-4085-ba0d-54277841ad3a.jpg?1783931010",
    normalUrl:
      "https://cards.scryfall.io/normal/front/5/a/5ad36fb2-c44e-4085-ba0d-54277841ad3a.jpg?1783931010",
  },

  // `gameChanger: true` at rarity `common`: the bracket chip is a property of the card, never of
  // its rarity.
  {
    id: "3394cefd-a3c6-4917-8f46-234e441ecfb6",
    oracleId: "53236dd7-845a-444c-96d5-f41ed7325d8f",
    name: "Rhystic Study",
    setCode: "pcy",
    setName: "Prophecy",
    collectorNumber: "45",
    lang: "en",
    rarity: "common",
    layout: "normal",
    manaCost: "{2}{U}",
    cmc: 3,
    typeLine: "Enchantment",
    oracleText:
      "Whenever an opponent casts a spell, you may draw a card unless that player pays {1}.",
    colors: "U",
    colorIdentity: "U",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"not_legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"legal","paupercommander":"banned","penny":"not_legal","pioneer":"not_legal","predh":"legal","premodern":"legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"34.05","eur_foil":"196.45","tix":"4.68","usd":"70.24","usd_etched":null,"usd_foil":"389.99"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Terese Nielsen",
    illustrationId: "3129ebcd-58ab-4d7f-886d-a4cbbe30e1f6",
    releasedAt: "2000-06-05",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: true,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/3/3/3394cefd-a3c6-4917-8f46-234e441ecfb6.jpg?1783945789",
    normalUrl:
      "https://cards.scryfall.io/normal/front/3/3/3394cefd-a3c6-4917-8f46-234e441ecfb6.jpg?1783945789",
  },

  // `power: "*"`, `toughness: "1+*"` — the P/T that proves these columns are text.
  {
    id: "b6876d9e-0908-43ac-8542-09c7aa02b5ba",
    oracleId: "45900b2f-f6a9-4c42-9642-008f3c1cf6dd",
    name: "Tarmogoyf",
    setCode: "fut",
    setName: "Future Sight",
    collectorNumber: "153",
    lang: "en",
    rarity: "rare",
    layout: "normal",
    manaCost: "{1}{G}",
    cmc: 2,
    typeLine: "Creature — Lhurgoyf",
    oracleText:
      "Tarmogoyf's power is equal to the number of card types among cards in all graveyards and its toughness is equal to that number plus 1.",
    colors: "G",
    colorIdentity: "G",
    power: "*",
    toughness: "1+*",
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"8.84","eur_foil":"102.94","tix":"0.14","usd":"19.90","usd_etched":null,"usd_foil":"172.49"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Justin Murray",
    illustrationId: "abf5b6d9-61e7-47f0-b187-a6bdfec68f58",
    releasedAt: "2007-05-04",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/b/6/b6876d9e-0908-43ac-8542-09c7aa02b5ba.jpg?1783943094",
    normalUrl:
      "https://cards.scryfall.io/normal/front/b/6/b6876d9e-0908-43ac-8542-09c7aa02b5ba.jpg?1783943094",
  },

  // Phyrexian mana (`{1}{B/P}{B/P}`) — a hybrid the font *does* draw, so it pins the glyph path
  // beside the fallback below.
  {
    id: "064dfdeb-485f-473e-9fa0-8fdb7638cdc6",
    oracleId: "fd74f8eb-0253-42dd-8277-186d4934da38",
    name: "Dismember",
    setCode: "nph",
    setName: "New Phyrexia",
    collectorNumber: "57",
    lang: "en",
    rarity: "uncommon",
    layout: "normal",
    manaCost: "{1}{B/P}{B/P}",
    cmc: 3,
    typeLine: "Instant",
    oracleText:
      "({B/P} can be paid with either {B} or 2 life.)\nTarget creature gets -5/-5 until end of turn.",
    colors: "B",
    colorIdentity: "B",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"2.23","eur_foil":"16.77","tix":"4.66","usd":"3.96","usd_etched":null,"usd_foil":"26.78"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Terese Nielsen",
    illustrationId: "e16dc6cf-82ef-4073-98bd-4d3f1f461c96",
    releasedAt: "2011-05-13",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: true,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/0/6/064dfdeb-485f-473e-9fa0-8fdb7638cdc6.jpg?1783941314",
    normalUrl:
      "https://cards.scryfall.io/normal/front/0/6/064dfdeb-485f-473e-9fa0-8fdb7638cdc6.jpg?1783941314",
  },

  // Hybrid: `{R/W}{R/W}{R/W}`, three symbols each of which is two colours, and a `colors` string of
  // two letters that is not JSON.
  {
    id: "82a18b07-38b8-4854-9735-3cfe83b11bf1",
    oracleId: "5f079a75-899e-467d-b443-3b87ce2fb548",
    name: "Boros Reckoner",
    setCode: "gtc",
    setName: "Gatecrash",
    collectorNumber: "215",
    lang: "en",
    rarity: "rare",
    layout: "normal",
    manaCost: "{R/W}{R/W}{R/W}",
    cmc: 3,
    typeLine: "Creature — Minotaur Wizard",
    oracleText:
      "Whenever this creature is dealt damage, it deals that much damage to any target.\n{R/W}: This creature gains first strike until end of turn.",
    colors: "RW",
    colorIdentity: "RW",
    power: "3",
    toughness: "3",
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"legal","pioneer":"legal","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"0.30","eur_foil":"1.68","tix":"0.02","usd":"0.37","usd_etched":null,"usd_foil":"3.52"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Howard Lyon",
    illustrationId: "5204a467-e10e-4d30-8a2e-db6c7f8f4ddf",
    releasedAt: "2013-02-01",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/8/2/82a18b07-38b8-4854-9735-3cfe83b11bf1.jpg?1783940095",
    normalUrl:
      "https://cards.scryfall.io/normal/front/8/2/82a18b07-38b8-4854-9735-3cfe83b11bf1.jpg?1783940095",
  },

  // Plain multicolour — `{R}{W}`, two separate pips. Here because it is *not* hybrid: read from
  // memory it looks like one, and a fixture that conflated the two would leave `ms-rw` untested
  // while appearing to cover it.
  {
    id: "d4ddf9cc-40a7-4b4f-bb51-b08171453c9a",
    oracleId: "2679d0dd-ba30-4a1c-b6a0-b3ac6c790496",
    name: "Boros Charm",
    setCode: "gtc",
    setName: "Gatecrash",
    collectorNumber: "148",
    lang: "en",
    rarity: "uncommon",
    layout: "normal",
    manaCost: "{R}{W}",
    cmc: 2,
    typeLine: "Instant",
    oracleText:
      "Choose one —\n• Boros Charm deals 4 damage to target player or planeswalker.\n• Permanents you control gain indestructible until end of turn.\n• Target creature gains double strike until end of turn.",
    colors: "RW",
    colorIdentity: "RW",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"legal","predh":"not_legal","premodern":"not_legal","standard":"legal","standardbrawl":"legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"4.52","eur_foil":"8.81","tix":"0.03","usd":"5.84","usd_etched":null,"usd_foil":"13.25"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Zoltan Boros",
    illustrationId: "a31e2d3d-dd7c-4b92-95c4-92cbf512a962",
    releasedAt: "2013-02-01",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: true,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/d/4/d4ddf9cc-40a7-4b4f-bb51-b08171453c9a.jpg?1783940111",
    normalUrl:
      "https://cards.scryfall.io/normal/front/d/4/d4ddf9cc-40a7-4b4f-bb51-b08171453c9a.jpg?1783940111",
  },

  // `{8}{C/P}{C/P}` — colourless Phyrexian, one of only four tokens in the whole corpus `mana-font`
  // has no glyph for (measured 2026-08-09: `L`, `C/P`, `HW`, `D`). Mixed with a `{8}` that *does*
  // draw, so the braces fallback is pinned inline rather than as a whole line.
  {
    id: "8a5d0caf-8f15-4c25-958d-19ffc7ed462e",
    oracleId: "fd0592e0-021a-450f-b0fb-e4a242dc16bf",
    name: "Kozilek, Compleated",
    setCode: "mb2",
    setName: "Mystery Booster 2",
    collectorNumber: "502",
    lang: "en",
    rarity: "rare",
    layout: "normal",
    manaCost: "{8}{C/P}{C/P}",
    cmc: 10,
    typeLine: "Legendary Creature — Phyrexian Eldrazi",
    oracleText:
      "({C/P} can be paid with either {C} or 2 life.)\nWhen you cast this spell, each opponent gets two poison counters, then each opponent with more than two cards in hand discards cards equal to the difference.\nAnnihinfect (Whenever this creature attacks, defending player sacrifices a permanent for each poison counter they have.)",
    colors: "",
    colorIdentity: "",
    power: "12",
    toughness: "12",
    legalities:
      '{"alchemy":"not_legal","brawl":"not_legal","commander":"not_legal","competitivebrawl":"not_legal","duel":"not_legal","future":"not_legal","gladiator":"not_legal","historic":"not_legal","legacy":"not_legal","modern":"not_legal","oathbreaker":"not_legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"not_legal","tlr":"not_legal","vintage":"not_legal"}',
    prices:
      '{"eur":"0.56","eur_foil":null,"tix":null,"usd":"0.44","usd_etched":null,"usd_foil":null}',
    finishes: '["nonfoil"]',
    faces: "[]",
    artist: "Will Liu",
    illustrationId: "ad890b05-cd44-4eb0-94e5-2aac5f3d260a",
    releasedAt: "2024-08-02",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: '["legendary"]',
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/8/a/8a5d0caf-8f15-4c25-958d-19ffc7ed462e.jpg?1783910538",
    normalUrl:
      "https://cards.scryfall.io/normal/front/8/a/8a5d0caf-8f15-4c25-958d-19ffc7ed462e.jpg?1783910538",
  },

  // `{HW}` — half-white, the second glyph-less token, and a mana value of **0.5**. A mana-value
  // chip that assumes integers rounds this into the wrong bucket.
  {
    id: "90f17b85-a866-48e8-aae0-55330109550e",
    oracleId: "b0d1c34c-30f1-4c07-9527-38b49231eb9f",
    name: "Little Girl",
    setCode: "unh",
    setName: "Unhinged",
    collectorNumber: "16",
    lang: "en",
    rarity: "common",
    layout: "normal",
    manaCost: "{HW}",
    cmc: 0.5,
    typeLine: "Creature — Human Child",
    oracleText: "",
    colors: "W",
    colorIdentity: "W",
    power: ".5",
    toughness: ".5",
    legalities:
      '{"alchemy":"not_legal","brawl":"not_legal","commander":"not_legal","competitivebrawl":"not_legal","duel":"not_legal","future":"not_legal","gladiator":"not_legal","historic":"not_legal","legacy":"not_legal","modern":"not_legal","oathbreaker":"not_legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"not_legal","tlr":"not_legal","vintage":"not_legal"}',
    prices:
      '{"eur":"0.17","eur_foil":"14.71","tix":null,"usd":"0.29","usd_etched":null,"usd_foil":"14.15"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Rebecca Guay",
    illustrationId: "fa376327-cd38-4f28-a8ab-7f61cf35a455",
    releasedAt: "2004-11-19",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "silver",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/9/0/90f17b85-a866-48e8-aae0-55330109550e.jpg?1783944262",
    normalUrl:
      "https://cards.scryfall.io/normal/front/9/0/90f17b85-a866-48e8-aae0-55330109550e.jpg?1783944262",
  },

  // Mana value 15 — the `8+` chip's bucket, and the widest curve bar a deck can have.
  {
    id: "67600383-bbb8-411c-b8e6-2296650bc747",
    oracleId: "900ca697-ad38-4b2b-bc74-2ff7eb6ea951",
    name: "Emrakul, the Aeons Torn",
    setCode: "roe",
    setName: "Rise of the Eldrazi",
    collectorNumber: "4",
    lang: "en",
    rarity: "mythic",
    layout: "normal",
    manaCost: "{15}",
    cmc: 15,
    typeLine: "Legendary Creature — Eldrazi",
    oracleText:
      "This spell can't be countered.\nWhen you cast this spell, take an extra turn after this one.\nFlying, protection from spells that are one or more colors, annihilator 6\nWhen Emrakul is put into a graveyard from anywhere, its owner shuffles their graveyard into their library.",
    colors: "",
    colorIdentity: "",
    power: "15",
    toughness: "15",
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"banned","competitivebrawl":"legal","duel":"banned","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"banned","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"banned","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"not_legal","vintage":"legal"}',
    prices:
      '{"eur":"24.15","eur_foil":"115.46","tix":"3.02","usd":"28.34","usd_etched":null,"usd_foil":"194.70"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Mark Tedin",
    illustrationId: "77d49e83-98fd-440e-a4ee-ecf8c5535899",
    releasedAt: "2010-04-23",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/6/7/67600383-bbb8-411c-b8e6-2296650bc747.jpg?1783942013",
    normalUrl:
      "https://cards.scryfall.io/normal/front/6/7/67600383-bbb8-411c-b8e6-2296650bc747.jpg?1783942013",
  },

  // Mana value 8: the first value the `8+` bucket contains, which is the off-by-one the chip is
  // most likely to get wrong.
  {
    id: "ba149706-cd17-4da6-8403-ccfe2d6cb437",
    oracleId: "216cb26e-8da9-478b-bfbc-8030f7adee72",
    name: "Avacyn, Angel of Hope",
    setCode: "avr",
    setName: "Avacyn Restored",
    collectorNumber: "6",
    lang: "en",
    rarity: "mythic",
    layout: "normal",
    manaCost: "{5}{W}{W}{W}",
    cmc: 8,
    typeLine: "Legendary Creature — Angel",
    oracleText:
      "Flying, vigilance, indestructible\nOther permanents you control have indestructible.",
    colors: "W",
    colorIdentity: "W",
    power: "8",
    toughness: "8",
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"not_legal","vintage":"legal"}',
    prices:
      '{"eur":"23.13","eur_foil":"76.60","tix":"0.02","usd":"39.89","usd_etched":null,"usd_foil":"88.90"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Jason Chan",
    illustrationId: "e4cb9f8d-fdf1-47ef-a393-a5b3f76d9e00",
    releasedAt: "2012-05-04",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/b/a/ba149706-cd17-4da6-8403-ccfe2d6cb437.jpg?1783940743",
    normalUrl:
      "https://cards.scryfall.io/normal/front/b/a/ba149706-cd17-4da6-8403-ccfe2d6cb437.jpg?1783940743",
  },

  // Mana value 7 — the last bucket that is its own chip.
  {
    id: "b66390d6-1649-4bfa-92d3-77664650d552",
    oracleId: "958d71ff-c9f7-46f0-96ca-79e7f4d65a16",
    name: "Elesh Norn, Grand Cenobite",
    setCode: "nph",
    setName: "New Phyrexia",
    collectorNumber: "9",
    lang: "en",
    rarity: "mythic",
    layout: "normal",
    manaCost: "{5}{W}{W}",
    cmc: 7,
    typeLine: "Legendary Creature — Phyrexian Praetor",
    oracleText:
      "Vigilance\nOther creatures you control get +2/+2.\nCreatures your opponents control get -2/-2.",
    colors: "W",
    colorIdentity: "W",
    power: "4",
    toughness: "7",
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"not_legal","vintage":"legal"}',
    prices:
      '{"eur":"17.35","eur_foil":"60.79","tix":"0.11","usd":"24.07","usd_etched":null,"usd_foil":"77.81"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Igor Kieryluk",
    illustrationId: "7618066e-d3fe-4ee5-aeea-f4e73a256ec0",
    releasedAt: "2011-05-13",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/b/6/b66390d6-1649-4bfa-92d3-77664650d552.jpg?1783941327",
    normalUrl:
      "https://cards.scryfall.io/normal/front/b/6/b66390d6-1649-4bfa-92d3-77664650d552.jpg?1783941327",
  },

  // Mana value 6, at rarity `special` — the other rarity with no colour token.
  {
    id: "da566bc8-6350-481d-99aa-9cea76da2a56",
    oracleId: "311a449d-dc74-46e6-9a47-6a597931f736",
    name: "Consecrated Sphinx",
    setCode: "mp2",
    setName: "Amonkhet Invocations",
    collectorNumber: "8",
    lang: "en",
    rarity: "special",
    layout: "normal",
    manaCost: "{4}{U}{U}",
    cmc: 6,
    typeLine: "Creature — Sphinx",
    oracleText: "Flying\nWhenever an opponent draws a card, you may draw two cards.",
    colors: "U",
    colorIdentity: "U",
    power: "4",
    toughness: "6",
    legalities:
      '{"alchemy":"not_legal","brawl":"not_legal","commander":"legal","competitivebrawl":"not_legal","duel":"legal","future":"not_legal","gladiator":"not_legal","historic":"not_legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"legal","pioneer":"not_legal","predh":"legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"not_legal","tlr":"not_legal","vintage":"legal"}',
    prices:
      '{"eur":null,"eur_foil":"149.75","tix":"0.20","usd":null,"usd_etched":null,"usd_foil":"164.95"}',
    finishes: '["foil"]',
    faces: "[]",
    artist: "Lius Lasahido",
    illustrationId: "bbfd0fde-3e25-457d-a359-638a13805371",
    releasedAt: "2017-04-28",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "borderless",
    gameChanger: true,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/d/a/da566bc8-6350-481d-99aa-9cea76da2a56.jpg?1783936432",
    normalUrl:
      "https://cards.scryfall.io/normal/front/d/a/da566bc8-6350-481d-99aa-9cea76da2a56.jpg?1783936432",
  },

  // Nonfoil only, colourless, one generic pip: the plainest row in the corpus and the one a layout
  // regression shows up on first.
  {
    id: "4cbc6901-6a4a-4d0a-83ea-7eefa3b35021",
    oracleId: "6ad8011d-3471-4369-9d68-b264cc027487",
    name: "Sol Ring",
    setCode: "c21",
    setName: "Commander 2021",
    collectorNumber: "263",
    lang: "en",
    rarity: "uncommon",
    layout: "normal",
    manaCost: "{1}",
    cmc: 1,
    typeLine: "Artifact",
    oracleText: "{T}: Add {C}{C}.",
    colors: "",
    colorIdentity: "",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"not_legal","commander":"legal","competitivebrawl":"not_legal","duel":"banned","future":"not_legal","gladiator":"not_legal","historic":"not_legal","legacy":"banned","modern":"not_legal","oathbreaker":"banned","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"not_legal","tlr":"legal","vintage":"restricted"}',
    prices:
      '{"eur":"0.88","eur_foil":null,"tix":"0.06","usd":"1.74","usd_etched":null,"usd_foil":null}',
    finishes: '["nonfoil"]',
    faces: "[]",
    artist: "Mike Bierek",
    illustrationId: "146aaae4-93f4-409a-be32-010e86d137da",
    releasedAt: "2021-04-23",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: true,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/4/c/4cbc6901-6a4a-4d0a-83ea-7eefa3b35021.jpg?1783927506",
    normalUrl:
      "https://cards.scryfall.io/normal/front/4/c/4cbc6901-6a4a-4d0a-83ea-7eefa3b35021.jpg?1783927506",
  },

  // **Foil only.** A quick-add that offers nonfoil for every card writes an entry that then prices
  // through a `usd` key this blob does not have.
  {
    id: "16a2c470-b2b8-4633-89b1-7b936bcaff8d",
    oracleId: "6ad8011d-3471-4369-9d68-b264cc027487",
    name: "Sol Ring",
    setCode: "sld",
    setName: "Secret Lair Drop",
    collectorNumber: "913",
    lang: "en",
    rarity: "rare",
    layout: "normal",
    manaCost: "{1}",
    cmc: 1,
    typeLine: "Artifact",
    oracleText: "{T}: Add {C}{C}.",
    colors: "",
    colorIdentity: "",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"not_legal","commander":"legal","competitivebrawl":"not_legal","duel":"banned","future":"not_legal","gladiator":"not_legal","historic":"not_legal","legacy":"banned","modern":"not_legal","oathbreaker":"banned","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"not_legal","tlr":"legal","vintage":"restricted"}',
    prices: '{"eur":null,"eur_foil":null,"tix":null,"usd":null,"usd_etched":null,"usd_foil":null}',
    finishes: '["foil"]',
    faces: "[]",
    artist: "Lē Yamamura",
    illustrationId: "2bd486cb-845b-4269-9771-05e7d21c4b52",
    releasedAt: "2025-12-01",
    imageStatus: "highres_scan",
    promo: true,
    fullArt: true,
    frameEffects: '["inverted"]',
    borderColor: "borderless",
    gameChanger: false,
    everUncommon: true,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/1/6/16a2c470-b2b8-4633-89b1-7b936bcaff8d.jpg?1783904689",
    normalUrl:
      "https://cards.scryfall.io/normal/front/1/6/16a2c470-b2b8-4633-89b1-7b936bcaff8d.jpg?1783904689",
  },

  // All three finishes at once (`nonfoil`, `foil`, `etched`) — the finish picker's full row.
  {
    id: "1920dae4-fb92-4f19-ae4b-eb3276b8dac7",
    oracleId: "cc187110-1148-4090-bbb8-e205694a39f5",
    name: "Counterspell",
    setCode: "mh2",
    setName: "Modern Horizons 2",
    collectorNumber: "267",
    lang: "en",
    rarity: "uncommon",
    layout: "normal",
    manaCost: "{U}{U}",
    cmc: 2,
    typeLine: "Instant",
    oracleText: "Counter target spell.",
    colors: "U",
    colorIdentity: "U",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"legal","paupercommander":"legal","penny":"not_legal","pioneer":"not_legal","predh":"legal","premodern":"legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"1.69","eur_foil":"2.15","tix":"0.03","usd":"2.95","usd_etched":"3.25","usd_foil":"3.19"}',
    finishes: '["nonfoil","foil","etched"]',
    faces: "[]",
    artist: "Zack Stella",
    illustrationId: "1044055e-a362-4edb-8101-96655e15da95",
    releasedAt: "2021-06-18",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: true,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/1/9/1920dae4-fb92-4f19-ae4b-eb3276b8dac7.jpg?1783926788",
    normalUrl:
      "https://cards.scryfall.io/normal/front/1/9/1920dae4-fb92-4f19-ae4b-eb3276b8dac7.jpg?1783926788",
  },

  // Etched only, and `usd` is null while `usd_etched` is not: the price chain must read the
  // finish's own key rather than falling back.
  {
    id: "02d6e71c-e401-4e5b-a4b9-d67c21bd1b7c",
    oracleId: "c415bfdd-3d42-4f94-9f93-7e310becbc8b",
    name: "Restart Sequence",
    setCode: "acr",
    setName: "Assassin's Creed",
    collectorNumber: "211",
    lang: "en",
    rarity: "uncommon",
    layout: "normal",
    manaCost: "{3}{B}",
    cmc: 4,
    typeLine: "Sorcery",
    oracleText:
      "Freerunning {1}{B} (You may cast this spell for its freerunning cost if you dealt combat damage to a player this turn with an Assassin or commander.)\nReturn target creature card from your graveyard to the battlefield.",
    colors: "B",
    colorIdentity: "B",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"not_legal","commander":"legal","competitivebrawl":"not_legal","duel":"legal","future":"not_legal","gladiator":"not_legal","historic":"not_legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"not_legal","tlr":"not_legal","vintage":"legal"}',
    prices:
      '{"eur":null,"eur_foil":null,"tix":"0.02","usd":null,"usd_etched":"2.07","usd_foil":null}',
    finishes: '["etched"]',
    faces: "[]",
    artist: "Lie Setiawan",
    illustrationId: "f1b51fc5-2fd3-45a1-9d98-d1337247ab40",
    releasedAt: "2024-07-05",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: '["inverted","etched"]',
    borderColor: "black",
    gameChanger: false,
    everUncommon: true,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/0/2/02d6e71c-e401-4e5b-a4b9-d67c21bd1b7c.jpg?1783910921",
    normalUrl:
      "https://cards.scryfall.io/normal/front/0/2/02d6e71c-e401-4e5b-a4b9-d67c21bd1b7c.jpg?1783910921",
  },

  // White, uncommon, one pip, one sentence of rules text — the short end of the oracle-text box.
  {
    id: "b6bafa7b-62a4-477c-b2f5-6b9d26c6cbf4",
    oracleId: "b1544f21-7e98-461b-aed5-e748b0168c52",
    name: "Swords to Plowshares",
    setCode: "ema",
    setName: "Eternal Masters",
    collectorNumber: "32",
    lang: "en",
    rarity: "uncommon",
    layout: "normal",
    manaCost: "{W}",
    cmc: 1,
    typeLine: "Instant",
    oracleText: "Exile target creature. Its controller gains life equal to its power.",
    colors: "W",
    colorIdentity: "W",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"banned","legacy":"legal","modern":"not_legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"legal","premodern":"legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"1.16","eur_foil":"2.82","tix":"0.07","usd":"1.76","usd_etched":null,"usd_foil":"4.02"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Terese Nielsen",
    illustrationId: "d591934a-c68a-47e6-b207-d24c65af9440",
    releasedAt: "2016-06-10",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: true,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/b/6/b6bafa7b-62a4-477c-b2f5-6b9d26c6cbf4.jpg?1783937624",
    normalUrl:
      "https://cards.scryfall.io/normal/front/b/6/b6bafa7b-62a4-477c-b2f5-6b9d26c6cbf4.jpg?1783937624",
  },

  // Green, common, a 1/1 body: the ordinary creature every P/T column is sized for.
  {
    id: "581b7327-3215-4a4f-b4ae-d9d4002ba882",
    oracleId: "68954295-54e3-4303-a6bc-fc4547a4e3a3",
    name: "Llanowar Elves",
    setCode: "dom",
    setName: "Dominaria",
    collectorNumber: "168",
    lang: "en",
    rarity: "common",
    layout: "normal",
    manaCost: "{G}",
    cmc: 1,
    typeLine: "Creature — Elf Druid",
    oracleText: "{T}: Add {G}.",
    colors: "G",
    colorIdentity: "G",
    power: "1",
    toughness: "1",
    legalities:
      '{"alchemy":"legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"legal","paupercommander":"legal","penny":"not_legal","pioneer":"legal","predh":"legal","premodern":"legal","standard":"legal","standardbrawl":"legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"0.27","eur_foil":"2.73","tix":"0.03","usd":"0.33","usd_etched":null,"usd_foil":"3.83"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Chris Rahn",
    illustrationId: "82c0ea68-cf37-41ec-aec7-123e8e9f05d3",
    releasedAt: "2018-04-27",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/5/8/581b7327-3215-4a4f-b4ae-d9d4002ba882.jpg?1783934977",
    normalUrl:
      "https://cards.scryfall.io/normal/front/5/8/581b7327-3215-4a4f-b4ae-d9d4002ba882.jpg?1783934977",
  },

  // A planeswalker: mythic, four loyalty abilities, 362 characters of oracle text (measured
  // 2026-08-09) — the long end of the same box.
  {
    id: "0e606072-a3aa-4300-ba90-ec92a721fa76",
    oracleId: "7f77a84e-5a4b-4834-aefa-3cecc175ae8e",
    name: "Jace, the Mind Sculptor",
    setCode: "wwk",
    setName: "Worldwake",
    collectorNumber: "31",
    lang: "en",
    rarity: "mythic",
    layout: "normal",
    manaCost: "{2}{U}{U}",
    cmc: 4,
    typeLine: "Legendary Planeswalker — Jace",
    oracleText:
      "+2: Look at the top card of target player's library. You may put that card on the bottom of that player's library.\n0: Draw three cards, then put two cards from your hand on top of your library in any order.\n−1: Return target creature to its owner's hand.\n−12: Exile all cards from target player's library, then that player shuffles their hand into their library.",
    colors: "U",
    colorIdentity: "U",
    power: null,
    toughness: null,
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"legal","duel":"legal","future":"not_legal","gladiator":"legal","historic":"legal","legacy":"legal","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"not_legal","vintage":"legal"}',
    prices:
      '{"eur":"15.35","eur_foil":"156.69","tix":"0.56","usd":"24.84","usd_etched":null,"usd_foil":"220.97"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Jason Chan",
    illustrationId: "b0ab416a-c7a8-4531-8e6a-00a167db4f76",
    releasedAt: "2010-02-05",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/0/e/0e606072-a3aa-4300-ba90-ec92a721fa76.jpg?1783942061",
    normalUrl:
      "https://cards.scryfall.io/normal/front/0/e/0e606072-a3aa-4300-ba90-ec92a721fa76.jpg?1783942061",
  },

  // Mythic at one mana, with five of the six price keys filled — only `usd_etched` is null, because
  // it has no etched printing. The row a price column reads with almost nothing missing.
  {
    id: "a9738cda-adb1-47fb-9f4c-ecd930228c4d",
    oracleId: "37108cd4-bbab-4ce3-9ed6-f60e8422e703",
    name: "Ragavan, Nimble Pilferer",
    setCode: "mh2",
    setName: "Modern Horizons 2",
    collectorNumber: "138",
    lang: "en",
    rarity: "mythic",
    layout: "normal",
    manaCost: "{R}",
    cmc: 1,
    typeLine: "Legendary Creature — Monkey Pirate",
    oracleText:
      "Whenever Ragavan deals combat damage to a player, create a Treasure token and exile the top card of that player's library. Until end of turn, you may cast that card.\nDash {1}{R} (You may cast this spell for its dash cost. If you do, it gains haste, and it's returned from the battlefield to its owner's hand at the beginning of the next end step.)",
    colors: "R",
    colorIdentity: "R",
    power: "2",
    toughness: "1",
    legalities:
      '{"alchemy":"not_legal","brawl":"legal","commander":"legal","competitivebrawl":"banned","duel":"banned","future":"not_legal","gladiator":"legal","historic":"banned","legacy":"banned","modern":"legal","oathbreaker":"legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"legal","tlr":"legal","vintage":"legal"}',
    prices:
      '{"eur":"34.63","eur_foil":"41.84","tix":"8.78","usd":"42.19","usd_etched":null,"usd_foil":"57.08"}',
    finishes: '["nonfoil","foil"]',
    faces: "[]",
    artist: "Simon Dominic",
    illustrationId: "a1c86e0c-da57-4905-b29a-940c73de37a6",
    releasedAt: "2021-06-18",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: '["legendary"]',
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: false,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/a/9/a9738cda-adb1-47fb-9f4c-ecd930228c4d.jpg?1783926839",
    normalUrl:
      "https://cards.scryfall.io/normal/front/a/9/a9738cda-adb1-47fb-9f4c-ecd930228c4d.jpg?1783926839",
  },

  // An Alchemy rebalance: `digital: true`, so the search's `paperOnly` default has a second thing
  // to hide and the two are not one set's quirk.
  {
    id: "f5fce9a5-85ae-408e-a260-b1e39843626e",
    oracleId: "995b4d53-8932-4739-a77d-2a1cae3f02ad",
    name: "A-Vivi Ornitier",
    setCode: "fin",
    setName: "Final Fantasy",
    collectorNumber: "A-248",
    lang: "en",
    rarity: "mythic",
    layout: "normal",
    manaCost: "{1}{U}{R}",
    cmc: 3,
    typeLine: "Legendary Creature — Wizard",
    oracleText:
      "{T}: Add X mana in any combination of {U} and/or {R}, where X is Vivi Ornitier's power.\nWhenever you cast a noncreature spell, put a +1/+1 counter on Vivi Ornitier and it deals 1 damage to each opponent.",
    colors: "RU",
    colorIdentity: "RU",
    power: "0",
    toughness: "3",
    legalities:
      '{"alchemy":"legal","brawl":"legal","commander":"not_legal","competitivebrawl":"legal","duel":"not_legal","future":"not_legal","gladiator":"not_legal","historic":"legal","legacy":"not_legal","modern":"not_legal","oathbreaker":"not_legal","oldschool":"not_legal","pauper":"not_legal","paupercommander":"not_legal","penny":"not_legal","pioneer":"not_legal","predh":"not_legal","premodern":"not_legal","standard":"not_legal","standardbrawl":"not_legal","timeless":"not_legal","tlr":"not_legal","vintage":"not_legal"}',
    prices: '{"eur":null,"eur_foil":null,"tix":null,"usd":null,"usd_etched":null,"usd_foil":null}',
    finishes: '["nonfoil"]',
    faces: "[]",
    artist: "Toni Infante",
    illustrationId: "0c6fb581-2a08-4e71-8b6f-cce243d92eef",
    releasedAt: "2025-10-28",
    imageStatus: "highres_scan",
    promo: false,
    fullArt: false,
    frameEffects: null,
    borderColor: "black",
    gameChanger: false,
    everUncommon: false,
    digital: true,
    artCropUrl:
      "https://cards.scryfall.io/art_crop/front/f/5/f5fce9a5-85ae-408e-a260-b1e39843626e.jpg?1783905124",
    normalUrl:
      "https://cards.scryfall.io/normal/front/f/5/f5fce9a5-85ae-408e-a260-b1e39843626e.jpg?1783905124",
  },
];
